### PR TITLE
Change selection box boundary

### PR DESCRIPTION
**Pull request by pivotalgeorge**
Mainly the right and bottom bounds seemed misaligned from the column and row gridlines.

**We were seeing:**
screen shot 2017-05-24 at 11 15 10 am

**our changes leave us with:**
screen shot 2017-05-24 at 11 16 51 am

Please try the modified cellrangedecorator and let us know if it looks good.

### CODE REVIEW

**Comment by 6pac** [comment]
It's looking perfect as it is now on my computer in the latest versions of Chrome and Microsoft Edge on Windows 10.
Are you sure it's not the result of a cascading style from elsewhere?
Have you tried the basic ```example-spreadsheet.html``` as a check that it's not a style issue?

**Comment by shrutiyer** [comment]
@6pac We tried removing all the CSS on our side and apparently something is still offsetting the selection box.
If we changed this PR to allow for these offsets to be set via options, would that be an acceptable PR?

**Comment by 6pac** [comment]
Perhaps, but let's exhaust all other options first:
- what browser are you using?
- have you loaded up ```example-spreadsheet.html ``` from the repo on your local drive or [here](http://6pac.github.io/SlickGrid/examples/example-spreadsheet.html) to check a standard case?

**Comment by shrutiyer** [comment]
Currently, we are seeing this issue only in our code on all the browsers. We checked that example that you pointed us to and indeed it works correctly.

In our application, we are using slickgrid in different places and the ability to customize some of the properties would allow us to keep the original source code without having to fork it. Especially, if the only difference between the original source code and the one that fit our need are just offsets.

**Comment by 6pac** [comment]
yeah, that sounds reasonable. there is an ```options``` object to play with, so I suppose it's quite straightforward. Please go ahead.

**Comment by shrutiyer** [comment]
@6pac We updated the PR to use the `options`.

**Pull request merged**
