### PR TITLE
Fix(slick.grid): Replace jQuery appendTo with js append for renderRows

### PR DESCRIPTION
**Pull request by RasmusBergHogia**
When my company tested the security of one of our applications, we found that we had missed to sanitize the values we send to Aurelia SlickGrid. We then also discovered that SlickGrid was not protected by the set Content Security Policy in the application, when script tags were run. After further investigation it turns out it's due to the jQuery function AppendTo being used. Which runs script tags automatically when they are appended. 

This PR does not replace all jQuery AppendTo, or for that matter fixes every places where CSP can not protect. It would been too much work for my company to put resources on, instead it only covers the part where we have dynamic data.

More information about this problem: 
https://csp.withgoogle.com/docs/faq.html#caveats
https://docs.wpvip.com/technical-references/security/javascript-security-recommendations/

### CODE REVIEW

**Comment by 6pac** [comment]
Happy to pull if this passes tests. @ghiscoding?

**Comment by ghiscoding** [comment]
I would have to test that out later today by running all Cypress E2E tests of Aurelia-Slickgrid unless @RasmusBergHogia have done that already?

**Comment by RasmusBergHogia** [comment]
> 
> 
> I would have to test that out later today by running all Cypress E2E tests of Aurelia-Slickgrid unless @RasmusBergHogia have done that already?

I run them once, but some weird way some duplicate if-sats was there after I commit, so I run cypress the tests again.

**Comment by ghiscoding** [comment]
What was the part you used in Aurelia-Slickgrid causing this security issue? I have sanitized a few area of the lib with DOM Purify, mostly Editor/Filter

**Comment by RasmusBergHogia** [comment]
> 
> 
> > I would have to test that out later today by running all Cypress E2E tests of Aurelia-Slickgrid unless @RasmusBergHogia have done that already?
> 
> I run them once, but some weird way some duplicate if-sats was there after I commit, so I run cypress the tests again.

Oh, sorry didn't read you meant run Cypress tests Aurelia-SlickGrid. I don't have that repos download yet. Probly will not have the time to run the tests today.

**Comment by ghiscoding** [comment]
I just click on accept to run the CI here and all the Cypress tests are failing here, so I expect they would also fail on Aurelia-Slickgrid, your change seems to have a big impact

**Comment by RasmusBergHogia** [comment]
> 
> 
> What was the part you used in Aurelia-Slickgrid causing this security issue? I have sanitized a few area of the lib with DOM Purify, mostly Editor/Filter

Was my colleague investigate that, which is on parental leave so I don't really know what was wrong on the build in sanitizing in Aurelia SlickGrid with DomPurify. We are doing before we doing a DomPurify sanitizing before adding data as it's now.

**Comment by ghiscoding** [comment]
@RasmusBergHogia so I'm not sure if you saw but after I ran the GitHub Actions CI in this PR nearly all Cypress tests failed, we won't be able to merge your code if that's the case because you will make thousand of users unhappy (me included) :P  At least I'm happy the Cypress tests I've put are catching these issues early on

**Comment by 6pac** [comment]
I was a little suspicious of the code - it appears to ```.add()``` the wrong element. For example, should 

     rowsCache[rows[i]].rowNode = $()
                    .add($(x.firstChild))
                    .add($(xRight.firstChild));

be 

     rowsCache[rows[i]].rowNode = $()
                    .add($canvasBottomL)
                    .add($canvasBottomR);

?

**Comment by RasmusBergHogia** [comment]
> @RasmusBergHogia so I'm not sure if you saw but after I ran the GitHub Actions CI in this PR nearly all Cypress tests failed, we won't be able to merge your code if that's the case because you will make thousand of users unhappy (me included) :P At least I'm happy the Cypress tests I've put are catching these issues early on

I saw, and I try understand why they failed in the short time had between meetings yesterday. When I try some of the failing test manually they works, totally fine. I will investigate this further, even if I have low knowledge in Cypress at the moment.

> I was a little suspicious of the code - it appears to `.add()` the wrong element. For example, should
> 
> ```
>  rowsCache[rows[i]].rowNode = $()
>                 .add($(x.firstChild))
>                 .add($(xRight.firstChild));
> ```
> 
> be
> 
> ```
>  rowsCache[rows[i]].rowNode = $()
>                 .add($canvasBottomL)
>                 .add($canvasBottomR);
> ```
> 
> ?

Has been some years between I last write jQuery, but what I understand you add the appended elements to the array in existing solution. And it brokes totally if try add parent elements instead:
Screenshot_278

**Comment by RasmusBergHogia** [comment]
I think find the issue, but can't get the cypress test to run on my computer. So I can't test it automatic locally, but what could see that the rows got messy (with some cell data left from before) on rerendering (at least was the problem when paging was in use).

Screenshot_279

And when I move the appending part to after adding children to array, the mess was gone:
Screenshot_280

So can you run Cypress tests again?

**Comment by ghiscoding** [comment]
Why is the Task # different than Task 50 on your first row though? That is wrong and I'm not sure if it's being caught by the Cypress test. What problem do you have installing Cypress? Have you tried deleting the `node_modules` and reinstalling?

**Comment by RasmusBergHogia** [comment]
> 
> 
> Why is the Task # different than Task 50 on your first row though? That is wrong and I'm not sure if it's being caught by the Cypress test. What problem do you have installing Cypress? Have you tried deleting the `node_modules` and reinstalling?

It was a totally messup with elements over each other in the cells, Task 50 is there too. So elements are not getting clean as it should So what I missed when change the jQuery code native JS the which order the elements should be append.

I got Cypress running, didn't thought I could start server and start Cypress in same terminal. 
Every tests was green what I can see:
Screenshot_281

**Comment by ghiscoding** [comment]
@RasmusBergHogia as long as that Task 50 is back to its original position then I'm fine with this PR, the next step would be test in both of my libs (Aurelia-Slickgrid and Slickgrid-Universal), I prefer to play safe and run tests on all libs. 

@6pac could you go in the project "Settings" and change the GitHub Actions to run for every users (by default it won't run for new contributors without us approving the run) 
image

**Comment by 6pac** [comment]
done

**Comment by ghiscoding** [comment]
@RasmusBergHogia @6pac 
I ran the Cypress in all 3x libs that I have and all Cypress tests are passing (Aurelia-Slickgrid has about 500 Cypress tests), so I think it's fair to say that the PR is ok. 

LGTM, feel free to merge

**Pull request merged**
