### PR TITLE
Fix grid scrolling using mouse wheel, when frozen column/row is set after the grid is initialised

### PR DESCRIPTION
**Pull request by jadjare**
When the grid initialises it only handles the mouse wheel if either frozen columns or frozen rows have been set.  This results in a bug, whereby if frozen columns or rows are set after the grid has initialised, then placing the mouse over the frozen area and using the scroll wheel results in no scrolling.  In this circumstance it will only scroll when the mouse is placed in the non frozen area.  

Always handling the mousewheel, when the jQuery mouseWheel plugin is set, fixes this issue.

### CODE REVIEW

**Comment by ghiscoding** [comment]
Have you tested on a regular grid (without any frozen feature enabled), we need to make sure that it doesn't affect regular grids.

**Comment by jadjare** [comment]
I have tested on a regular grid, without frozen rows / columns, to make sure that the scroll doesn't double up.  It doesn't seem to, it scrolls one row at a time.

I did wonder whether it'd be safe to remove the condition on frozen columns/rows, as I guessed the line of code above, e.g. `$viewport.on("scroll", handleScroll)`, is what normally handles scrolling.  However, I figured that when frozen columns / rows are applied, as the grid initialises, both handlers would be in operation anyway.

I guess the alternative approach would be to turn on/off mousewheel event handling in the grid.setScroller() or grid.setOptions() methods, depending on whether frozen areas are on or off.

**Comment by ghiscoding** [comment]
I'll have to take time to test this with a few grids before approving the PR. Hopefully in the coming days.

**Comment by jadjare** [comment]
@ghiscoding, 
> Is it supposed to fix an issue where the mouse wheel is supposed to work in some regions where it currently doesn't?

Yes, that's exactly the problem the pull request should fix.

**Comment by ghiscoding** [comment]
@6pac I'm ok with merging this PR, it doesn't break anything and I tested a few grids with/without frozen feature and it's seems all fine.

**Pull request merged**
