### PR TITLE
Fix #176 add customizable picker title for i18n purposes

### LINKED ISSUE #176: i18n via config
Suggestion: it would be nice to have all labels that are actually hardcoded in application (ex. 'Force fit columns', 'Synchronous resize', 'Page n of n', 'items per page', 'n-n of n items') configurables via configuration object.

### PR DESCRIPTION
**Pull request by ghiscoding**
As the title says, it brings customization of certain text titles for i18n purposes. There are 2 controls affected by this PR (ColumnPicker and GridMenu). They both had fixed English texts embedded in the code and that made it hard to change them to other languages (i18n). 

This PR brings 2 new titles (they are optional) that are optionally customizable (if nothing is provided, they will remain with the current defaults).
- forceFitTitle: "Force fit columns",         // default to "Force fit columns"
- syncResizeTitle: "Synchronous resize" // default to "Synchronous resize"

Since there are defaults provided, this change will be totally transparent to most users, it will just adds possible customization to user who wants to change these text.

### CODE REVIEW

**Comment by 6pac** [comment]
Thanks once again. I actually made these changes too, in response to the issue, but you did a better job so you get the gong.
I'm hereby giving you commit to the repo (once I work out how to do it!).
Lemme know if you ever need a sounding board.

**Comment by ghiscoding** [comment]
Oh thanks for that, my first time in a shared Github repo :)
I saw you created a new release, awesome!

**Comment by 6pac** [comment]
Me too, I think! Welcome ...

**Comment by ghiscoding** [comment]
I think you didn't publish the latest version on NPM. Should I just publish or are you running anything special?

**Comment by 6pac** [comment]
Yes, go ahead, I just forgot. Am working on a script to do all the publishing stuff (there's quite a lot), but I'm new to SED and AWK, so it's a learning experience.
BTW, what OS are you using? I'm assuming Bash is the go for cross platform scripting, I'm running Git on Windows 10 using MinGW (but then Win10 is running in a VirtualBox VM on OsX on a mac).

**Comment by ghiscoding** [comment]
After thinking about it, I don't think I can push to your local NPM.

I'm on Windows 10 as well, I do most of these commands with regular DOS shell (powershell works too). For Git, I just use Visual Studio Code editor, it's free and it has Git embedded, I can commit and push to branches right from the editor. I rarely run any Git command directly, but when I have to then I can just open Git Shell. If you install [Git for Windows](http://gitforwindows.org), you will get the Git Shell as well. If you want to use a UI Tool, you can look at another free tool called [Source Tree](https://www.atlassian.com/software/sourcetree) which is from Atlassian (an Australian company, local to you hehe). Oh if you are just looking at NPM Publishing script, you can use Visual Studio Code as well for that, just configure a [task.json](https://code.visualstudio.com/Docs/editor/tasks) or take a look at mine for publishing Angular-Slickgrid, here's my [task.json](https://github.com/ghiscoding/Angular-Slickgrid/blob/master/.vscode/tasks.json), you can run them simply through VSCode just mouse clicks :)

**Comment by ghiscoding** [comment]
I made a quick PR for a VSCode task and some quick instructions, check PR #180

**Pull request merged**
