### PR TITLE
fix: few minor fixes on plugin with menus

### PR DESCRIPTION
**Pull request by ghiscoding**
- make sure commands/options are defined and also allow `false` to work as it should
- also make the cellMenu/contextMenu work with just options set (without any commands)

### CODE REVIEW

**Comment by 6pac** [comment]
can I ask why the change from ```x || ""``` to  ```x !== undefined ? x : ""``` ?

**Comment by ghiscoding** [comment]
@6pac yeah so if `x` is `false` it would go on the right side, so 
- if `x = false` then `x || ""` would return `""`
- if `x = false` then `x !== undefined ? x : ""` would return `x`

**Comment by 6pac** [comment]
Sure. Won't ```item.command``` and ```item.option``` always be either a string or undefined, though?  
I doesn't really matter, I'm not familiar with this plugin and probably shouldn't have an opinion.

**Comment by ghiscoding** [comment]
I had an `item.option` that its value was `false` and wasn't working because the associated option was an empty string instead the real value that was supposed to be `false`

**Comment by 6pac** [comment]
No worries, I suppose Typescript would have avoided that conversation .... ;-)

**Comment by ghiscoding** [comment]
@6pac 
indeed TypeScript is awesome 😉 

Question, are you going to have time to look at that PostAsync cleanup PR #495 this week? 
If not, I might ask for another release without it, I'm ready for releasing new versions of my libs on my end but really wish to have a new version on your side first.

**Comment by 6pac** [comment]
I'm really busy at the moment, I didn't want to merge the issue just because I know if I do, I'll probably never get back to it. However, I may be a while fixing it, so I think I'd better just merge it and release, and then make a note to go back later :-o

Feel free to hassle me in a couple of weeks if I haven't done it.

**Comment by ghiscoding** [comment]
If we're talking about couple weeks, then I would rather have a new version now and wait for the post async in a few weeks in a separate version. I really wish to do new release this week so... up to you to merge and release or release without it, as long as I see a new version this week I would be quite happy 😄

**Pull request merged**
