### PR TITLE
Fix: Really replace jQuery append with native append for renderRows

### PR DESCRIPTION
**Pull request by RasmusBergHogia**
Unfortunately, I must have made a mistake when I tested my previous PR. For scripts run automatically still when they get appended. This is because the elements that are appended to are a jQuery HtmlElement, and therefore they don't use native append but jQuery append method.

So the new PR take out the html element first, and then make a append on it instead.

### CODE REVIEW

**Comment by ghiscoding** [comment]
can you remove the `package-lock.json` file from your PR? Because that might break the GitHub Actions CI since your push seems to empty that file

**Comment by RasmusBergHogia** [comment]
I can remove the update on that file, but what I can see it doesn't empty it out.

**Review by ghiscoding — APPROVED** [review]

**Comment by ghiscoding** [comment]
@RasmusBergHogia 
I should have tried on my end (I did not before today with the new SlickGrid version) because it breaks on my side, it breaks in our Salesforce environment and also on some of the Slickgrid-Universal Cypress tests (I assume most probably Aurelia-Slickgrid as well). Have you ran any Cypress tests when changing this code (apart from SlickGrid tests)? Because at this point, we might have to rollback on this...

cc @6pac

**Comment by RasmusBergHogia** [comment]
@ghiscoding I run cypress test for SlickGrid only, has not SlickGrid Universal and Aurelia SlickGrid project setup locally.
Though it was safe change, sorry about the mess a have made. Hope you find a solution, unfortunately over my knowledge about SlickGrid and Salesforce. And I understand if you need rollback...

**Comment by ghiscoding** [comment]
@RasmusBergHogia it's ok, there's actually 2 issues in that same [Example](http://6pac.github.io/SlickGrid/examples/example-frozen-rows.html) so it's a 2 in 1 😉

**Pull request merged**
