### PR TITLE
- OuterWdith() is used instead of width() which fixes issues with Bootst...

### PR DESCRIPTION
**Pull request by afromogli**
...rap 3:s box-sizing: border-box. Described more in detail in issue: https://github.com/mleibman/SlickGrid/issues/742

### CODE REVIEW

**Comment by afromogli** [comment]
One thing I forgot to test was to run SlickGrid without Bootstrap 3... So be sure to test that! (Or close this pull request :P )

**Comment by 6pac** [comment]
I left some comments on #742. This is in my queue of things to look at, but the fix is easy, just disable border-box for the slickgrid elements. I have to do regression testing.

**Comment by afromogli** [comment]
Ok, I actually tried to disable border-box using CSS (the fix is mentioned in https://github.com/mleibman/SlickGrid/issues/742 by jcready) but it did not work... So be sure to do regression testing with and without Bootstrap 3!

**Comment by skosch** [comment]
FWIW, this patch doesn't work for me with Bootstrap 3 :(

**Comment by afromogli** [comment]
@skosch Hmm... strange, it worked for me.. Have you doublechecked that you have replaced all instances of width() with outerWidth()?

**Comment by skosch** [comment]
You know what, after trying it again, it does work—once I resize one of the columns, that is, everything jumps into the right place. The autosize function does the trick, too.

(Unfortunately I now have another problem, namely that multiple grids on the same page all assume the same column widths ...)

**Comment by afromogli** [comment]
Great news! Strange regarding the same column widths for multiple grids, we are also running multiple grids on same page without having this issue.. Did this issue appear after you used this fix?

**Comment by skosch** [comment]
After ironing out a bunch of other problems, that problem has now disappeared. It seems like it was caused by jQuery selectors erroneously catching elements across mutliple grids, due to some weird interactions with another library I am using.

Note that for the header sizes to work properly, I also had to comment out the [first `if` block in `measureCellPaddingAndBorder`](https://github.com/mleibman/SlickGrid/blob/master/slick.grid.js#L894) (which was responsible for setting `headerColumnWidthDiff` incorrectly), in addition to replacing the `width()`s with `outerWidth()`s. Hopefully this helps the next guy ...

**Comment by 6pac** [comment]
I have now patched this problem and written a blog post. Release 2.2.3 includes the fix.
https://github.com/6pac/SlickGrid/releases
http://low-bandwidth.blogspot.com.au/2015/06/slickgrid-with-jqueryui-and-bootstrap.html

**Comment by tanveer-ali** [comment]
I have to still enable the following slick.grid.css after getting the patch from @6pac in order to work in firefox the first grid loads .. it was misaligned

/box-sizing: content-box !important;/
to
box-sizing: content-box !important;

But enabling it fixed the issue. I am using jquery-ui-1.11.3 and bootstrap 3.3.4

**Pull request closed without merging**
