### PR TITLE
Remove TreeColumns code from grid and core

### PR DESCRIPTION
**Pull request by 6pac**
The TreeColumns code appears to have been added by accident. This pull request removes it from the codebase. It appears to exist only in ```slick.grid.js``` and ```slick.core.js```.

### CODE REVIEW

**Comment by ghiscoding** [comment]
@6pac  it wasn't by accident, I've never really understood what the TreeColumns does exactly, but it was added when we merged the code from X-Slickgrid to get Frozen feature (from this [line](https://github.com/ddomingues/X-SlickGrid/blob/d4d80978d31a5a4200221960e30b903cdbde7add/slick.core.js#L479-L485) in X-SlickGrid). I don't really know why it was created by I know it came from X-SlickGrid and now we can see that a bunch of Cypress tests are failing after your change. I'm not sure this is a good idea to remove it at this time, I would rather wait a bit longer since this seems more like a possible breaking change and perhaps might be better to wait for the PR to remove jQuery (your PR would also introduce a lot of more conflicts in that jQuery PR).

**Comment by 6pac** [comment]
OK, take your point about not complicating things for the jQuery extraction, although I must admit I was hoping to simplify it a little bit!  
Either way, I'm happy to leave it till later if it will cause problems. I'm keen to do it though, so I will investigate the failing tests - will have to educate myself about Cypress now.

**Comment by 6pac** [comment]
I'm still working on the hidden columns changes. Surprisingly, they seem to mostly be working with just the basic logic changes. I'm appreciating your previously proposed approach, which seems cumbersome at first but sidesteps a lot of the issues nicely. Once I'm done, you can have a look and if you don't like it, perhaps we go back to your PR.

**Comment by ghiscoding** [comment]
yeah even if I agree that it would be nice to eventually remove this Tree, I would prefer to wait to avoid breaking changes. I'm waiting for a new release to close a few of my lib PRs and I certainly wouldn't want to introduce breaking change now that I'm so close to be bug free.

Side note, keep going with PRs, it's easier to review and debug... and don't forget to be on `master` branch when creating a new release. Cheers

**Comment by 6pac** [comment]
No worries. I'm feeling like I should do a release now - I think the hidden columns PR is going to be a little complex. But at the same time I don't want to release your suggested PR (with the different ```columns``` methods until we can make an informed choice between the two options.

Shall I just do a release with the codebase as it is now?

**Comment by ghiscoding** [comment]
@6pac yes I definitely want a new release, I was waiting for a new release to close my lib issues. :)

**Comment by 6pac** [comment]
Hey @ghiscoding, just checking here before I open an issue to make sure I haven't done something stupid.  For me, ```example-frozen-rows``` is taking a long time to render when I open the page (maybe 5-6 seconds). I've had a look and tracked it down to line 4335 in ```slick.grid.js``` - ```frozenBottom``` is true and the frozen row is set to -5. It's then rendering everything from there to the end of the dataset, ie. all 50,000 rows. 

There's clearly a bug somewhere, but I just wanted to run this past you before I do anything else.

**Comment by ghiscoding** [comment]
@6pac I know one of the example is quite long to load since it has a lot of columns and lots of data, it does seem to be longer when the frozen portion is at the bottom and when you combine that with bottom & left frozen then it's even longer (which I believe that example uses both with lots of data, so yeah it's long).

Would you mind going ahead with a release with only what is currently merged, I'd really like to close my lib issues that I have open for more than a week. We can work out the other PRs later without rushing them. Thanks mate

**Pull request closed without merging**
