### PR TITLE
option for skipping scrollbarDimensions

### PR DESCRIPTION
**Pull request by lucax88x**
option for not including the scrollbar dimensions on the width/height…

### CODE REVIEW

**Comment by lucax88x** [comment]
I have a particular case where I have 3 grids, where only the 3rd grid shows the scrollbar and navigates the others.

If I hide the scrollbar, I have an hole on the grids because scrollbar dimensions are fixed on the library, I have added an option to skip these dimensions.

**Comment by 6pac** [comment]
strange, I've been thinking of this issue.
i was thinking of adding a scrollbar space mode: 
(a) always leave space, 
(b) never leave space (though I don't think it's possible to ensure the scrollbar is always hidden - if there are enough rows it will always appear, but I suppose if you know there won't be extra rows then it will always be hidden), 
(c) autosize
however i'm not sure we can respond to the scrollbar being shown or hidden (i think it's part of the 'overflow' process). will have to look into that.

**Comment by lucax88x** [comment]
as you said, we cannot respond to the "shown"/"hidden" fact of the scrollbar, I really don't think there's a way.

your "space modes" a and b are the thing I have achieved on my little PR.

anyway, my case was a weird one:

image

I have 6 slickgrids, top 3 and bottom 3, had to split them because the central part is dynamic and scrollable.

I have obviously hidden the  vertical scrollbars on  1, 2 and horizontal scrollbars on 2

The visible vertical scrollbar on 3 navigates 1 and 2, the visible horizonzal scrollbar on 4 navigates the 2

I had an hole on the vertical scrollbar of 1 and 2, so I had to disable the scrollDimensions on the library with an option.

hope this does make sense to you :)

**Comment by 6pac** [comment]
https://github.com/mleibman/SlickGrid/issues/1171

**Pull request closed without merging**
