### PR TITLE
feat: add npm scripts to create new version release & npm publish

### PR DESCRIPTION
**Pull request by ghiscoding**
Add npm scripts to automate version releases, it will follow the steps shown below
1. Ask for version bump type
2. Bump version in "package.json" and "slick.grid.js"
3. Run minify script and add the new version number to each minified file headers
4. Create/Update changelog.md
5. Update (sync) npm lock file with new version
6. Add all changed files to Git ("package.json", "slick.grid.js", "CHANGELOG.md" and all minified files)
7. Create git tag of the new release
8. Commit all files changed to git
9. Push git tags and all commits to remote origin
10. NPM publish
11. Create a Release on GitHub with changelog and new tag

Also created the `CHANGELOG.md` of all previous versions and commits that followed [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). Note that it adds a lot of devDependencies and I could maybe create a separate npm lib for that in the future but for now that will do

Here's a quick preview, we obviously cannot not show all steps below (also the git changes are only shown as a demo, everything is automated even the git add & commits)
Code_c5fEEl7UDM

### CODE REVIEW

**Comment by ghiscoding** [comment]
@6pac 
So here's the promised PR to automate github/npm releases, the entire list of steps it follows is shown in the description of the PR. Could you please do a quick review of the steps and if you're satisfied, could you then merge the PR, git checkout on your computer this `next` branch and publish a new alpha 3.0.0 version, it should be as simple as following these steps
1. merge PR
2. git checkout the `next` branch on your computer with latest code
3. npm install all deps
4. execute release script 
    - `npm run release`  
    - if you prefer to do a dry-run test, you can use `npm run preview:release` but be sure to discard git changes once you're done, they are part of the dry-run to show which files get changed (also note that all minified files will change since there's date timestamp every time the minify script runs)
5. from the increment version prompt, please choose
    - "premajor.alpha (3.0.0-alpha.0)"
6. follow all instructions and if all goes well, it should publish a new 3.0 alpha versions on npm with an alpha tag
   - **note:**  at some point in time in the instruction, you will get a link which will prefill a form to create a GitHub Release, so make sure to click the link, it might be a long link. We can automate this part even more in the future, I'll show you how later.

Obviously I could not test every commands, especially for pushing to github and doing npm publish, but hopefully all goes well (crossing my fingers).

**Comment by yamass** [comment]
One thing I don't quite like about this is where to put the reference to the ticket number (#xyz) that a commit fixes, for traceability. The spec puts to footer which makes it necessary to expand the commit message in order to get that link. I'd rather put it right into the title. What do you think?

**Comment by ghiscoding** [comment]
@yamass I'm not exactly sure what you're talking about, Conventional Changelog is used by millions of project and was created by a different team (see their [Conventional-Changelog](https://github.com/conventional-changelog) GitHub), the changelog are created by using templates, which we don't control, and the most popular template is "angular" and I've been using it in all my projects for years and it's fine by me as long as PRs follow the simple guideline. Currently SlickGrid does not have any changelog, so this PR is a big improvement on that side, the rest of this PR is management stuff and mostly intended for @6pac's use

**Comment by yamass** [comment]
@ghiscoding Let me clarify.

I agree that we don't control the spec. I also agree that using conventional changelog is a good idea and helps a lot.

However, the spec (both the raw spec and the angular template) explicitly states that the ticket reference goes to the footer. Fortunately, the spec does not forbid putting the ticket reference into the title (which I would prefer).

Anyhow, what I did not know a few hours ago is that it is established practice to still put the ticket reference into the title. As an example, take a look at the angular commit log. 

image

So my question is: Is it OK to do so in this project?

**Comment by 6pac** [comment]
@ghiscoding what do you mean exactly by 'npm install all deps'
I'm an NPM newb.

**Comment by ghiscoding** [comment]
@6pac I just mean to run `npm install` 😉 there's a lot of new devDependencies for the release scripts, so make sure to run the install, that's what I meant

**Comment by 6pac** [comment]
$ npm run release

> slickgrid@2.4.45 release
> node ./scripts/release.js --create-release github

G:\Dropbox\Work\SlickGrid\SlickGrid-6pac\scripts\git-utils.js:74
        throw Error('Working tree has uncommitted changes, please commit or remove the following changes before continuing.');
              ^

Error: Working tree has uncommitted changes, please commit or remove the following changes before continuing.
    at Object.hasUncommittedChanges (G:\Dropbox\Work\SlickGrid\SlickGrid-6pac\scripts\git-utils.js: 74:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (G:\Dropbox\Work\SlickGrid\SlickGrid-6pac\scripts\release.js:43:3)

**Comment by 6pac** [comment]
$ git status
On branch next
Your branch is up-to-date with 'origin/next'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        examples/test1.html
 
nothing added to commit but untracked files present (use "git add" to track)

**Comment by 6pac** [comment]
So, I have untracked files but the working tree is not dirty.

**Comment by ghiscoding** [comment]
yeah it will error out if you have files that aren't committed yet, it runs this git command to know this
```sh
git status --porcelain
```

https://github.com/6pac/SlickGrid/blob/017bc7fde29745197c3a52d01f296f51ac58af94/scripts/git-utils.js#L70-L76

Are you able to cleanup the branch with nothing uncommit before you run the release? If it's a problem, we can maybe disable that line temporarily, technically speaking it will add only the files touched by the release script into git, every other files will be excluded from the git commit of the release

**Comment by 6pac** [comment]
So I've got a heap of untracked files that I have put in temporarily for debugging purposes, such as the ```examples/test1.html``` (I edited out the other 20 or so). These are not part of the repo. GIT will let you stage specific files for commit and just ignores these untracked ones (so I don't have any staged uncommitted files, only unstaged uncommitted files - this is what I interpret as 'clean').

Could we use:

    git status -uno --porcelain

noting that the git man pages specifically say that the porcelain versions shouldn't be used in scripting

**Comment by 6pac** [comment]
OK I've committed a change to ```git-utils.js``` for ```execArgs = ```:

    async function hasUncommittedChanges({ cwd, dryRun, skipChecks }) {
      const execArgs = ['status', '--porcelain', '-uno'];
      const { stdout } = await childProcess.exec('git', execArgs, { cwd });
      if (stdout.length && !skipChecks) {
          throw Error('Working tree has uncommitted changes, please commit or remove the following changes before continuing.');
      }
    }

That's fixed the untracked files issue, but now I'm finding the option selection is not working. I checked out your screen video above, and for me it's not moving the selection prompt for me on right/left/up/down arrow. I could possibly fix this, but I'm feeding this back so we can both be across it. I'm assuming probably inquirer is not installed. Shouldn't I be getting a message to that effect?

**Comment by ghiscoding** [comment]
@6pac  damn what's happening with your computer? lol 
Inquirer is part of the devDependencies so it should be installed, I think I've seen somewhere that some terminals aren't working good with it though so give it a try with a different terminal like powershell maybe (Git Bash for windows is probably having issues as pointed out in their GitHub [issue](https://github.com/SBoudrias/Inquirer.js/issues/921))

> "Git bash" on Windows is one of the rare terminals we cannot support. The problem is it is not a true interactive terminals which makes it incompatible with the redrawing of the screen inquirer is doing.

**Comment by 6pac** [comment]
OK, but I suspect a quite a number of people will be using that terminal! There doesn't appear to be a way to detect if we're running on that. Can I suggest a simpler approach like the LetEncrypt SSL tool?


    C:\deploy-bundles\LetsEncrypt>wacs
    
     A simple Windows ACMEv2 client (WACS)
     Software version 2.1.22.1267 (release, pluggable, standalone, 64-bit)
     Connecting to https://acme-v02.api.letsencrypt.org/...
     Scheduled task looks healthy
     Please report issues at https://github.com/win-acme/win-acme
    
     N: Create certificate (default settings)
     M: Create certificate (full options)
     R: Run renewals (0 currently due)
     A: Manage renewals (4 total)
     O: More options...
     Q: Quit
    
     Please choose from the menu:

**Comment by ghiscoding** [comment]
No one but you will be running this script, it`s to create a new SlickGrid version release (not even me will be running this script, I created it to help you with releases). We can also add letter choice with Inquirer but I prefer the arrow, because with letter choice it adds them in the question (please choose nmraoq) which looks a bit funny

image


Are you able to continue at least? I'd really like to have an alpha or beta 3,0 released so that I can continue the implementation in my libs. Thanks

**Comment by 6pac** [comment]
So there were a number of roadblocks with the release script (you can read about them in the commit history if you're interested) but I finally got through them. *unfortunately*, it had been so long since reading the initial instructions that I just did the 3.0.0. release, not the pre-alpha. Damn.

I happen to know you can't delete or overwrite NPM tags so what do you think I should do now? I can remove the Git push and the tags and do a pre-alpha, but that's not going to remove the NPM release.  
I'm sorry for this-should have been paying more attention but I got kind of sucked down the debugging rabbit hole.

BTW, I am more than happy for you to do releases with the script - I think it's best if we are both set up for that.

Also, thanks for the scripts! It has been really great for me to be forced to use NPM and see modern javascript in action. Unfortunately a few of my clients use IE11 still, so I've not used ES6 in production and still haven't seen a lot of its features. They are way cool. And it's triggered me to start up a test TypeScript/Nodejs VS solution to check out the tooling and debugging. This could be the start of my next technological leap. I note with interest that ts can compile to either ES5 or ES6.

I feel like I might appear to be a bit of a dinosaur, but I can learn new languages and dev environments very quickly. It's just that I've been a professional dev since 1986, so I've seen a hell of a lot of frameworks and trends come and go in the sector, and I have to be impressed by something *and* convinced of its commercial sense before I commit the time and resouces to learn it and possibly to retool to it. That's (unfortunately) a fairly high bar to clear.

**Comment by ghiscoding** [comment]
to rollback a version, you can reach out to the npm team [here](https://www.npmjs.com/support) (I did in the past), it`s best if no one downloaded the version yet (I did not on my side). There're usually pretty quick to reply and do the action

As for the script, I couldn't test everything because the end goal is a release and I don't have access to that (at least not in npm since I'm not a contributor there). I was able to test about 60% of the script. What problem did you encounter? Can you fix the issues in script for the next release to work? The goal is really to make it a lot simpler for you to release a new version and I'm pretty sure it would achieve this goal in the future

not a contributor on npm (I don't know who that other guy is either 😬)
image

**Pull request merged**
