### PR TITLE
Footer Click and Context Menu Events

### PR DESCRIPTION
**Pull request by ataft**
Add events for onFooterClick and onFooterContextMenu

### CODE REVIEW

**Comment by ghiscoding** [comment]
There's already an event for `onContextMenu`, why add another footer one? I remember that the original author at the end was trying to avoid adding too many of these events to subscribe because it could slow down the grid. So we need to have a good reason to add an another event

**Comment by ataft** [comment]
I double-checked, and onContextMenu and onClick are not called on footer right/left click.

I hear you about too many events. This one would only be added when `options.createFooterRow` is true. If events are causing performance problems, have you thought about making some or all of them dependent on whether or not someone subscribes to them?

**Comment by ghiscoding** [comment]
>  have you thought about making some or all of them dependent on whether or not someone subscribes to them?

If you have a way to do that, I'm sure that @6pac and I would be happy to see a PR for that. We are always happy to review code change that can increase performance, as long as it doesn't break anyone's code is our motto.

**Comment by ataft** [comment]
Great, since this only affects those that are using the footer, and it's a necessary feature for footer click/contextmenu, can you approve this PR?

As for improving performance via subscribe, it will probably take a bit more back and forth, but this PR is separate from that. Rather than using `grid.onEvent.subscribe(cb)`, what if people subscribed to events in the options, like this:
 
```
const options = {
    events: {
        'onFooterClick': someFunction
    }
};
```

Then, in `finishInitialization()` we do something like this:
```
if(options.events) {
    for (var key in options.events) {
        self[key] = new Slick.Event();
        self[key].subscribe(options.events[key]);
    }      
}
```

Lastly, on a per-event basis, we could use the options for logic like this:
```
if(options.events && options.events.onFooterClick) {
    $footerRow.on("click", handleFooterClick)
}
```

I implemented this locally and it works. I'm not sure how much of a performance gain this would allow, but it would certainly allow us to add more events without any performance hits unless users want that event. Thoughts?

**Comment by ghiscoding** [comment]
I would rather wait for @6pac to review this PR and approve (also your previous PR #414 that I reviewed but not merged)

**Comment by 6pac** [comment]
sorry guys, crazy busy as usual. I'll have time to look at these over the weekend...

**Comment by 6pac** [comment]
I'm not quite sure about the 'events slowing down the grid' issue. Nothing actually happens unless the user has subscribed; there's a very minimal amount of code in the call.  
I suspect it might have been referring to events that are called a lot, or that are attached to a DOM element that gets a lot of activity bubbling up. 

I might just be being thick, so explain it if I'm missing something.

**Comment by ghiscoding** [comment]
@6pac 
I thought I read somewhere by the author (Mleibman) that adding too many events is not good, but I can't really find that specific issue, so I must be wrong, but on the other hand I found this [issue](https://github.com/mleibman/SlickGrid/pull/768) which I felt really strong about not adding that event... anyhow, we're probably ok then.

**Comment by ataft** [comment]
Events are a potential problem. @ghiscoding, the one you mention above happens when the renderRows() function is called, which very frequent and directly related to virtual scrolling. Events like onClick are different in that manner.

To a degree, I think what @6pac says about not being a problem unless subscribed is true. However, you can still see that `.on` is called many times in `finishInitialization()`. As to my point, and code way above, we could also avoid .on being called if there's no subscribe. Currently this is not the case, .on is called regardless of subscribe.

In the end, event performance issues will be dependent on specific use cases. This is not one of them, but we should be wary

**Comment by 6pac** [comment]
Yeah, interesting issue @ghiscoding. But I think that does bear out my approach to this. With the speed of javascript these days, I think a single grid event or an ```.on``` event on a single DOM element is fine. It's just where events are called a lot (the render loop, or OnMouseMove) or apply to general DOM objects (I have had people want to apply OnMouseMove to the document object as part of the grid code!) where we can run into trouble.

Have to say, I've always been uneasy about the master-detail plugin, and the google groups discussion referenced above very clearly states what I have had a gut feeling about. TLDR; messing directly with the DOM is a can of worms.

**Pull request merged**
