### PR TITLE
Group Header Totals

### PR DESCRIPTION
**Pull request by ataft**
Option called includeHeaderTotals to show totals in group header row. When combined with "aggregateCollapsed: false", it makes for a very clean look when collapsed.

image

### CODE REVIEW

**Comment by ataft** [comment]
One thing I don't love is that the new `includeHeaderTotals` is a groupItemMetadataProvider option, but `aggregateCollapsed` and `displayTotalsRow` are DataView options. Should this new logic be put into the DataView rather than GroupItemMetadataProvider, or perhaps pass DataView options into the GroupItemMetadataProvider here: https://github.com/6pac/SlickGrid/blob/master/slick.dataview.js#L493

Thoughts?

**Comment by ataft** [comment]
@6pac Any love for this one? It looks a lot nicer, and fits twice as many rows as the current approach, shown here:

image

**Comment by 6pac** [comment]
Happy to pull this, but just thinking about the location of the options, as you have raised.  The DataView should be used only for data, and the MetadataProvider is used to bridge the gap between presentation and data. At the moment, we store temporary presentation data, particularly about group status, in the DataView. Strictly speaking this should be moved to the provider, but practically it does not hurt to store the data there, as long as it is kept separate from the primary data. 

It's a while since I looked over all this, so I may be wrong. However this is a roundabout way of saying that what you've proposed looks OK to me.

**Comment by ataft** [comment]
Right, that makes sense. I'll leave this as is. Once you merge, I'll update the docs with this new option

**Pull request merged**
