### PR TITLE
fix(build): couple of fixes caused by previous lint changes

### PR DESCRIPTION
**Pull request by ghiscoding**
ref #424

### CODE REVIEW

**Comment by 6pac** [comment]
did you read my earlier comment about ```var columns``` in columnpicker? There's a constructor function parameter with the same name. Really think we should do something about that.

**Comment by ghiscoding** [comment]
oh ok I see what you mean, let me try to remove the `var` again like you did and re-run my tests. I think it was actually ok with your code. Give me a minute.

**Comment by ghiscoding** [comment]
@6pac 
You were totally right on these `var`, I removed them back and only kept the changes for the drag & drop (the `undefined` change).

**Comment by 6pac** [comment]
so it would be handy if we had a de-facto standard that if you want to handle ```null``` or ```undefined``` that you use ```!= null```. i think it's clearer that way, because the necessity to do ```typeof(x) === 'undefined'``` occasionally, throws another ingredient into the mix. i think 99% of them are that way now, too.

**Comment by ghiscoding** [comment]
I might be wrong but I think the following 
```js
typeof var1 === "undefined"`
```
is equivalent to 
```js
var1 === undefined
```
but the latter is shorter to write

**Comment by 6pac** [comment]
@ataft caught me out on that a little while ago, it had been a while. the first always works, but the second throws an exception if the variable has not been *declared*.

**Comment by ghiscoding** [comment]
yes and your linting should have catch all the missing `var` now, so for most of them they should be declared

**Comment by ghiscoding** [comment]
@6pac 
Not sure if you saw that the PR was updated after your comment to remove duplicate `var columns` declaration. So this is ready and fixes the drag column to another position that throws an error in the console.

Also note, that this `if( limit !== undefined && limit !== null )` could also be changed to `if( limit)` and that would work too, and if we want to be bullet proof we could use `if(limit && limit.hasOwnProperty('start'))`

**Comment by 6pac** [comment]
I have switched to  ```if( limit)``` and applied the code locally to avoid the whitespace noise. About to re-release.

**Comment by ghiscoding** [comment]
Good I saw that, I'll close this PR then, thanks

**Pull request closed without merging**
