### PR TITLE
feat: add enableMouseWheelScrollHandler option to allow dynamic load

### PR DESCRIPTION
**Pull request by ghiscoding**
- when using TypeScript, we must always import the mousewheel jquery lib even if we don't need it because TypeScript does not yet support dynamic import. So providing a grid option to only use the mousewheel handler when we really want it is the only bulletproof way to only use that handler only when we really need it (typically when using a frozen grid)
- ref Angular-Slickgrid [issue](https://github.com/ghiscoding/Angular-Slickgrid/issues/618)

### CODE REVIEW

**Comment by 6pac** [comment]
I get the first change, but what was the second one around the $viewport events even doing? Looks like some kind of workaround.

**Comment by ghiscoding** [comment]
You mean this code ` var viewportEvents = $._data($viewport[0], "events");` ?
It's a trick that I found out while googling on how to know what events are registered, see this [SO](https://stackoverflow.com/a/2518441/1212166), this returns all events registered on that jQuery element that you provide as first argument.

In the code that I added, it basically does the following:
- check if the viewport element already has the `mousewheel` event handler associated
    - if Yes, then do nothing
    - if No, then add the mousewheel scroll handler

This avoids adding multiple event listeners for the same handler, which could be really bad and slow down the entire grid.

You might be wondering why am I doing that anyway? Because in my lib, we can add a freeze column at any point in time (see animated gif) and for that I use `grid.setOptions({ frozenColumn: 2: enableMouseWheelScrollHandler: true })` to freeze at column 2 and when I remove it then I use the `grid.setOptions({ frozenColumn: -1, enableMouseWheelScrollHandler: false })` which runs the 2nd piece of code that you were looking at... so basically dynamically adding the mousewheel scroll handler

hMkg3hCTo0

**Comment by 6pac** [comment]
OK, nice!

**Comment by 6pac** [comment]
And you'll be wanting a release?

**Comment by ghiscoding** [comment]
that would be nice too 😃

**Pull request merged**
