### PR TITLE
Collapse/Expand groups from draggable group Pane

### PR DESCRIPTION
**Pull request by muthukumarse**
Hey Bro,

added little feature to Collapse/Expand groups from draggable group Pane

Cheers, Muthu

### CODE REVIEW

**Comment by 6pac** [comment]
Looks good. I'd just like to move the part that's in ```slick.grid.js``` into the plugin, using the  ```onHeaderCellRendered``` event.

**Comment by muthukumarse** [comment]
sure. Please do that as you suggest. Thx

**Comment by muthukumarse** [comment]
hi, updated little more to use existing function from slick.grid.js

**Comment by muthukumarse** [comment]
Hey Bro,

I patched as you suggested, please have quick look and merge if you come good.

Cheers

**Comment by muthukumarse** [comment]
broken. will raise another PR

**Pull request closed without merging**
