### PR TITLE
Added option to disable columns options

### PR DESCRIPTION
**Pull request by caroph**
Added option to disable forceFitButton and syncResize button

### CODE REVIEW

**Comment by 6pac** [comment]
Perhaps I'm wrong, but shouldn't line 106 be

    if (!options.disableForceFitButton)) {

rather than

    if (!(options.columnPicker && options.columnPicker.disableForceFitButton)) {

Also, in an unrelated error from a previous commit (probably mine!), I think 

    var forceFitTitle = (options.columnPicker && options.columnPicker.forceFitTitle) || defaults.forceFitTitle;

should be 

    var forceFitTitle = (options.columnPicker && options.columnPicker.forceFitTitle) || options.forceFitTitle;

**Comment by 6pac** [comment]
Also, hate to be a nitpicker, but the option names should probably be ```hideXyz``` rather than ```disableXyz```

**Comment by ghiscoding** [comment]
@6pac I actually prefer to see the `disableForceFitButton` inside the `columnPicker` object. This object by me when I added new translation keys for the same buttons. As per the documentation, you can now do the following with the same `columnPicker` object. 
```javascript
   columnPicker: {
       columnTitle: "Columns",                 // default to empty string
         // the last 2 checkboxes titles
       disableForceFitButton: false,   
       forceFitTitle: "Force fit columns",     // default to "Force fit columns"
       disableSyncResizeButton: false,   
       syncResizeTitle: "Synchronous resize",  // default to "Synchronous resize"
   }
```
if we only do `options.disableForceFitButton`, we don't exactly know what this is for anymore. 

As for the last error you found in previous commit (it might be mine actually), I think it should be this instead
From
```javascript
    var forceFitTitle = (options.columnPicker && options.columnPicker.forceFitTitle) || defaults.forceFitTitle;
```
should be (we still want to use the default if nothing is found)
```javascript
    var forceFitTitle = (options.columnPicker && options.columnPicker.forceFitTitle) ? options.columnPicker.forceFitTitle : defaults.forceFitTitle;
```
This makes me think that we should probably do the same with the [gridMenu](https://github.com/6pac/SlickGrid/blob/master/controls/slick.gridmenu.js)

Also note that there's a newer PR #186 for this, not sure why this one here got closed.

**Comment by 6pac** [comment]
I'm trying  to get back to these ... this is superseded by #186 ... I agree with comments above, but just not with the use of ```default```: the ```default``` values all get copied over to the ```options``` variable in initialisation, so we're better off using ```options``` in case that's been changed since initialisation. Have I missed something?

**Comment by ghiscoding** [comment]
@6pac what the condition does is: first get the option title ELSE use the default title value.
That is working as expected, I added that line of code to support locale (i18n) and it's working as it should.

**Pull request closed without merging**
