### PR TITLE
fix: fix header/footer cell sizes when using fullWidthRows:true (#699)

### PR DESCRIPTION
**Pull request by yamass**
See #699

### CODE REVIEW

**Comment by ghiscoding** [comment]
Could you please change your commit title to follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) guidelines, it will be used in the near future to update our changelog and if it doesn't follow the guideline then it won't show up in the changelog (see #701)

FYI, we'll have to wait a bit before merging any new PRs because we are currently working on the next `major` version (see #695), however a quick question, have you tested your change with all types of grids? I assume you did, but just checking, it should work with all frozen types (top, bottom, left), regular grids with/without header and footers. You did remove a few lines, it seems more efficient but we'll have to make sure all grids are working. Thanks

**Comment by yamass** [comment]
I also changed the commit message according to the conventional commits spec.

**Comment by ghiscoding** [comment]
> I also changed the commit message according to the conventional commits spec.

hello, are you sure because I don't see the title changed

**Comment by yamass** [comment]
Yes, quite sure ;-)
https://github.com/6pac/SlickGrid/pull/700/commits/11f78face9302423fd846e3627fd07da6c192cba

**Comment by yamass** [comment]
Or would you like me to also change the title of this MR ticket?

**Comment by ghiscoding** [comment]
yes that's be better

**Comment by yamass** [comment]
Done.

**Comment by ghiscoding** [comment]
@yamass would it be possible to retest your change with the new version [3.0.0](https://github.com/6pac/SlickGrid/releases) that we just released. I don't see any merge conflicts but it's probably better if you can retest the UI with latest code. Thanks

**Comment by ghiscoding** [comment]
closing since I could not reproduce and the codebase changed a lot since then and will change even more when [Roadmap to v4.0](https://github.com/6pac/SlickGrid/discussions/743) is officially released

**Pull request closed without merging**
