### PR TITLE
feat(plugins): add ways to use all 3 plugins together, closes #347

### LINKED ISSUE #347: Using Checkboxes with DetailView
Need a way to use the expanding row and the checkboxes together.

Currently the row have issues when open that the rows in the checkbox plugin are some of the hidden rows in the expanding rows.

Waiting on the changes for the checkboxes to deal with disabled checkboxes then will need to find a way to deal with these.

@ghiscoding  input on how we can go about this would be great.

Thoughts so far an override functions so we can use the `id` of the data in the selected rows instead of it's index.

### PR DESCRIPTION
**Pull request by ghiscoding**
DO NOT MERGE YET - I still want to add Cypress E2E tests before merging

- closes #347
- this PR allows to use 3 plugins (RowDetail, RowMoveManager & CheckboxSelector) all at the same time. Our new project requires at least 2 of the 3 to be used together. 
- in order to achieve that, I added 2 new options to the Row Move Manager Plugin, the new options are (singleRowMove & disableRowSelection) and their default are set to false so it doesn't break anyone's code
- the main changes are done in the RowMoveManager plugin, while a couple of changes were also made in the RowDetail Plugin so that all 3 plugins all work nicely together. A new Example was added as well to demo all 3 plugins in 1 grid, Cypress E2E were also added

- [x] add a way to use all 3 plugins at the same time
- [x] add `usabilityOverride` to skip move icon displayed on each row for the RowMoveManager Plugin (same override as all other plugins)
- [x] add `getColumnDefinition()` method in the RowMoveManager Plugin with a custom formatter that is connected to the new `usabilityOverride` 
  - [x] should still work when user provide their own column definition (current behavior)
- [x] add `grid` object to the `args` parameter of `onMoveRows` and `onBeforeMoveRows`
- [x] add Cypress E2E tests

See animated gif below for a demo

iAwSJhB685

demo with `usabilityOverride` (RowMoveManager Plugin) to make only second rows moveable

image

### CODE REVIEW

**Comment by ghiscoding** [comment]
@6pac 
I'm done with this PR, there should be enough Cypress E2E to cover the behaviours. 
The explanation of the changes are mentioned on [top](https://github.com/6pac/SlickGrid/pull/474#issue-391929442)

Since there are a lot of commits, I strongly suggest you use the green "Squash and merge" button when merging. Would you mind doing another release, I'd like to pull the changes through NPM, thanks again mate.

**Comment by ghiscoding** [comment]
@6pac 
I saw that you went ahead quite fast on the release, that was awesomely fast, however there seems to be a slight problem as it still seems to point to the previous code. I also went and opened the `package.json` and it's still referring to `2.4.19`. I also did a delete of the package in `node_modules` but no luck, it still pulls previous code version. Was it too fast by any chance? ;)

**Comment by 6pac** [comment]
It's all 100% automated and worked flawlessly until recently. It seems I'm getting write or permissions failures somewhere in the process.
Dropbox stopped working a while back, I think Windows 10 has become unstable, and I need to reinstall :-(
I'll manually run this through again...but it will have to be this evening.

**Comment by ghiscoding** [comment]
Perhaps you forgot to update your local code before running `npm publish`? If so, we might need another version

Ahh ok you automate that process, that is about the only thing I still do manually hehe
Take your time, I'm going to bed anyway, it's past midnight here cheers mate

**Comment by 6pac** [comment]
hmmm. .. is it the new ```package.lock``` file that's the problem? I may not have integrated that into my processes yet. Everything else looks squeaky clean.

**Comment by ghiscoding** [comment]
@6pac 
No it's not related since the `package.lock` is for what the lib needs to download to work while the NPM bundle is what the lib export. For unknown reason it looks like the content of the NPM bundle still has the old bundle content and even the `package.json` shows `2.4.19` even though on the NPM website it does show `2.4.20`, there seems to be some lynching issues somewhere. I also tried on computer from work and I get the same result, still the old files are being downloaded. 

BTW, you can test it yourself too if you wish, just `npm install slickgrid` and a new folder and you'll see the content is not correct

So I think the best is to repackage (or rebundle) it and do another release.

**Comment by ghiscoding** [comment]
@6pac 
I saw you pushed another version `2.4.21` and tried it, unfortunately it's the same issue, I still code (content) from `2.4.19` so I don't see any new files code change since that version. That is really strange, I see the NPM tag is `2.4.21` but the content of it is really `2.4.19`. 

I made a commit to remove the `package-lock.json` from the NPM bundle (through `.npmignore`), hopefully, that can help?!

**Comment by 6pac** [comment]
no worries, I had just reached the same conclusion. When I ```npm install```ed, everything was good.

**Pull request merged**
