### PR TITLE
Accommodate string type numbers for MinAggregator & MaxAggregator

### PR DESCRIPTION
**Pull request by nickfogler**

### CODE REVIEW

**Comment by ghiscoding** [comment]
It looks like you've put your 2 PR into the same branch and so this PR includes the PR as well. I think they should be separate PR/branches since they modify different files. 

As for the code change itself, I think it's incorrect to use the `parseFloat` that way, since your cell value might be `null` in your dataset, and if that happens then the `parseFloat` will throw an error (I think). 

I think the following would be better (do the `parseFloat` after you validated that it is a number)
```diff
var val = item[this.field_];
      if (val != null && val !== "" && !isNaN(val)) {
        if (this.min_ == null || val < this.min_) {
-          this.min_ = val;
+          this.min_ = parseFloat(val);
        }
      }
```

**Comment by nickfogler** [comment]
Ya, sorry about the branch business.  I need to change the val to a number prior to `val < this.min` because comparing strings using the less than operators gives funky results (`'99' < '349'` is false, for example).

`parseFloat(null)` gives `NaN` so I think it's safe here.

**Comment by nickfogler** [comment]
I'm going to close this PR and open a new one isolating the correct changes....

**Comment by ghiscoding** [comment]
No worries, I made that exact same mistake a month ago in this repo lol

**Pull request closed without merging**
