### PR TITLE
 feat(grid): add alwaysShowVerticalScroll to fix Grid Menu side effect, closes #231

### LINKED ISSUE #231: UI problem with Grid Menu - is there a way to always have scroll on overflow-y ?
I'm facing some visual problems with the Grid Menu that I worked on. It works as expected when the dataset is big and there are scrolling. However when the dataset is small and no scrolling appears, the Grid Menu shows up over the headerRow (see print screen 1)

I'd like to always have the `overflow-y: scroll` but when I do that, the grid isn't resized properly and another scrolling appears for the X axis. It somehow fixes the missing text of last column J and the filter header (see print screen 2).

I tried searching in the code, but I don't have good luck in finding how to resize the viewport minus the scroll width, which is the same width as the Grid Menu. That might be great if we could have an option to always show scroll on the Y axis, that way the Grid Menu would always work (that is what the UI Grid lib does, see their [demo](http://ui-grid.info/docs/#!/tutorial/101_intro))

Column J header title and filter and not fully shown because of the Grid Menu overlapping, since Grid Menu requires scrolling (it takes same width as the scrolling bar)
gridmenu-noscroll

with scrolling always showing, it fixes Column J title and filter but I have to scroll left/right to see the entire grid. 
gridmenu-withscroll

So the last print screen shows that it's almost there, if only it could be without the X axis scrolling.

### PR DESCRIPTION
**Pull request by ghiscoding**
This PR closes #231

@6pac 
I did the following tests, to make sure it all works without affecting regular behavior
- add Grid Option with `alwaysShowVerticalScroll: true`
- add Grid Option with `alwaysShowVerticalScroll: false`
- don't include `alwaysShowVerticalScroll` flag in the options

If you want to see the UI side effect of no scrolling with Grid Menu, remove the `alwaysShowVerticalScroll` from the Grid Menu example and load 15 rows of data, you will see the overlapping of Grid Menu with data in background.

Also note, my editor has some default settings which removes any white space at the end of a line, so it shows a lot of diff. I hope you don't mind.

### CODE REVIEW

**Comment by ghiscoding** [comment]
@6pac 
Just a side note, I will soon go in vacations (leaving on coming Saturday) and will be unavailable for 3 weeks. So I just wanted to say, if there's any changes that needs to be done, I can do them this week or else in a month. There's no rush, I'm just saying that in case you might be wondering why I'm not answering, if that is next week or later.

Cheers mate

**Comment by 6pac** [comment]
Sorry, the whitespace did bug me (it's just the commit noise), but I applied all your changes here apart from that.

**Comment by ghiscoding** [comment]
Ok thanks Ben, I will make sure to disable this VSCode option in future PRs. 
Thanks again for re-applying the changes

**Comment by 6pac** [comment]
Just to be clear: I personally don't care about the whitespace, but I'm just concerned that for some people applying that patch may cause unnecessary conflicts. I thought you were on vacation!?

**Comment by ghiscoding** [comment]
lol yeah I am in vacation, but it's so hot here that I have some time during the day and I'm just reading, not doing any coding hehe

**Comment by ghiscoding** [comment]
@6pac
I think you forgot this line 
```diff
       var oldViewportHasVScroll = viewportHasVScroll;
       // with autoHeight, we do not need to accommodate the vertical scroll bar
-      viewportHasVScroll = !options.autoHeight && (numberOfRows * options.rowHeight > viewportH);
+      viewportHasVScroll = options.alwaysShowVerticalScroll || !options.autoHeight && (numberOfRows * options.rowHeight > viewportH);
       viewportHasHScroll = (canvasWidth > viewportW - scrollbarDimensions.width);
```

I'm not sure if the example would work without this change. 
You can see the code change on this [line](https://github.com/6pac/SlickGrid/pull/232/files#diff-7f1ab5db3c0316e19a9ee635a1e2f2d0L1988)

**Comment by 6pac** [comment]
Sorry. Updated.

**Comment by ghiscoding** [comment]
Awesome, thanks

**Comment by ghiscoding** [comment]
@6pac 
Thanks again for redoing the changes of this PR. 

Just curious, are you planning a new release in the short term? 
It's not a rush, I just need to know when the new version is out so that I can implement the fix on my side as well.

Thanks for all

**Comment by 6pac** [comment]
I probably should - there are a few bug fixes.

**Pull request closed without merging**
