### PR TITLE
inline Grouping 

### PR DESCRIPTION
**Pull request by muthukumarse**
added grouping just above grid header, where able to drag column into it to action

### CODE REVIEW

**Comment by 6pac** [comment]
Looks interesting. When submitting a significant feature like this, can you also include a new example page demonstrating it?

**Comment by muthukumarse** [comment]
Hi

Please review the changes,

- added example and done some clean up

Regards, Muthu

**Comment by 6pac** [comment]
Thanks Muthu, I'll get to this in a day or two. If it's not urgent, i get to it when i can. 
cheers, Ben

**Comment by muthukumarse** [comment]
Sure please do it. Bunch of our Developers wants to use and they are sitting different region. 

Regards, Muthu

**Comment by 6pac** [comment]
OK, I've reviewed this and I don't think it's suitable for merging as-is.
Thanks for the example though, that makes it sooo much easier!

I think the grid changes need to be merged separately and named in a more general way rather than specific to this feature.
IMO the code currently in the DataView should be in a separate plugin. 
There should not be a grid link in the DataView, the grid should be a parameter in the events (in theory, several grids may be driven from a DataView). In my repo, many of the grid events carry the grid as a final parameter.

Overall, it's neat but really a UI enhancement, and not one I'm sure everyone would want. That's why it should be a plugin.
Apologies that it's not going to make it into the repo soon. I'll add it to my list of things to integrate, but that list is pretty long.

**Comment by muthukumarse** [comment]
Will try to spend some time soon as you say then let see 

Regards, Muthu

**Comment by 6pac** [comment]
I'll keep you posted as I go. It's great that you are keen to do this. Possibly I can put together the shell and leave the final integration to you? It shouldn't be too hard, I think, most of the work is done.

**Comment by muthukumarse** [comment]
That's good idea, pl go ahead. 

Regards, Muthu

**Comment by 6pac** [comment]
just pushed a commit that has a version of this reworked into a plugin.
by the time i rearranged the structure of the files, it only took another half hour to get it working.

i've added a new 'preHeaderPanel' to the grid, which can be used for various things, not just this.
the grid option 'enableColumnReorder' now can take a function value, which if specified is the external function to call to set up column reorder. this is used for reordering in the example page.
finally, the code was shifted from the dataview to a new plugin.

so this was finally achieved with no mods to the DataView at all, and only generic mods to the Grid (adding a new header panel).

Could you please test this for any final issues.

**Comment by 6pac** [comment]
Maybe you'd like to credit yourself in comments in the plugin and example. That was quite a bit of work. Thanks!

**Comment by muthukumarse** [comment]
Ok sure, will test and let you know.

**Comment by muthukumarse** [comment]
closing this request, since requested from another branch

**Pull request closed without merging**
