### PR TITLE
fix: allow for multiple css class names, fixes #795

### LINKED ISSUE #795: jQuery change means you can no longer set space separated list of class names
Prior to the jQuery removal code in e.g. headerbutton.js was like this:
```
btn.addClass(button.cssClass);
```
I believe that "addClass" is a jQuery method. It accepts a space separated list of class names.
Now the code is like this:
```
btn.classList.add(button.cssClass);
```
This accepts only one class name. If you give is a space separated list of class names DOMTokenList complains. If you attempt to pass in an array of class names, you get a comma separated list of classnames out, and that's not valid syntax for the class attribute. DOMTokenList.add does allow a varargs list to be passed, but you would have to call it as
````
btn.classList.add(...button.cssClass);
````
But that would presumably only work if cssClass was an array.

Why do I want a list of classnames? Rather than using an image, I'm wanting to use an icon from an icon library like codicons, and that's done by specifying a list of class names, rather than an image file.

### PR DESCRIPTION
**Pull request by tomqwpl**
The previous behaviour with jQuery was that anywhere a class name was passed, jQuery allowed a space separated list of class names.
With "classList.add" this behaviour has to be explicitly added.

I believe all cases where ".split()" is used are already guarded against the classname not being falsy.
There were a couple of places where ".split" was used, but not the spread operator (...). This would result in a comma separated list of classnames being added. The assumption is that was a bug so I have fixed those.

I haven't changed any code in "dist", I assume that is handled as part of the release process in some way.

### CODE REVIEW

**Comment by tomqwpl** [comment]
Note that currently the cypress tests don't seem to run cleanly.

**Comment by tomqwpl** [comment]
OK. Cypress tests run cleanly now

**Comment by tomqwpl** [comment]
With these commits I can confirm that I can set a header button using a css class using code like:
```
cssClass: 'codicon codicon-refresh codicon-button header-cell-button refresh button',
```

**Comment by ghiscoding** [comment]
Thanks for the PR, the changes to the dist minified files wasn't necessary but that should still be fine. Thanks for the contribution.

**Review by ghiscoding — APPROVED** [review]

**Comment by ghiscoding** [comment]
I think it's safe to merge, so I'll go ahead and merge so that I can continue with other PRs

**Pull request merged**
