### PR TITLE
Fixed trailing commas, missing semi colons, and mix-matched format

### PR DESCRIPTION
**Pull request by vrad-joshuamckelvey**
Fixed trailing commas and missing semi colons for IE 8 compatibility.

Additionally, standardized code formatting.

If something is not to standards let me know.

### CODE REVIEW

**Comment by ghiscoding** [comment]
Sorry but we can't accept it the way it is, all your indentation is different. We use 2 spaces as indentation, can you please change it so that it doesn't have the entire file showing as changes. That is the standard we use

**Comment by 6pac** [comment]
Good call though. I've applied your changes (other than whitespace) and pushed to the repo. We'll do a release early next week.

@ghiscoding sorry to go OT here, but what are the things you're aware of that we need to put together for the next release? I've been super-busy last week or so but it's all back to normal now. Just getting my act together again...

**Comment by ghiscoding** [comment]
@6pac 
no worries, I got 2 PRs waiting for quick review, there's some comments in them if you could reply. Would be nice to have a release after the `console.log` are removed from the code. Thanks

**Comment by 6pac** [comment]
OK, will also change the sizing behaviour to mimic the legacy, that breakage was accidental.

**Comment by ghiscoding** [comment]
@vrad-joshuamckelvey 
Just wanted to say that I hope I wasn't too rude when I mention about the code standard that we use, we certainly welcome contributions. So I hope that this won't stop you from contributing in the future 😃 Thank you!

**Comment by 6pac** [comment]
Yeah, I find the indentation annoying too, but I think the sad fact is that everyone uses different indenting styles and everyone finds everyone else's styles annoying. As a result the policy I use is to leave it as you found it, and if you make changes, blend them into the style of the surrounding code.

**Comment by ghiscoding** [comment]
Yeah but just to point out, using indentation of 2 spaces is quite a lot the standard in most big project, which is what we use. You can see the [.editorconfig](https://github.com/angular/angular/blob/master/.editorconfig) of Angular which is a big player in the Framework world and that's what they use 2 spaces. It's just a bit crazy when indentation changes and GitHub sees that as a entire file change, which is scary when seeing this. However I know there's a checkbox to disregard spaces/indentation changes.

**Comment by 6pac** [comment]
All done. Can you @ghiscoding can you test the Legacy behaviour is now maintained? I'm not supporting that behaviour currently with the new settings, other than to use ```Legacy``` mode.
Legacy mode calls the old function in several places (on Init, resizeCanvas and updateRowCount) - new settings only call AutoSizeColumns on Init or by explicitly callling the function.

**Comment by ghiscoding** [comment]
@6pac 
As per my tests, it works when I pass the Legacy to the `autosizeColumns()` method (which is the method I always use), but doesn't work without it. Is that the behavior you wanted? I thought you meant that it was going to work without passing the Legacy as argument!? Anyhow, I'm ok using it with passing the Legacy argument anyway, it's not big of a deal, I counted 9 places in my entire lib to add this argument, so I'm ok with that.

**Comment by vrad-joshuamckelvey** [comment]
@ghiscoding No problem, thanks for letting me know the standards! I closed the PR since I wanted to fix the formatting to follow the repo standards, in the future should i just leave it open?

You guys are doing great work! @6pac @ghiscoding 

Looking forward to contributing to the repo.

**Comment by 6pac** [comment]
This is how it should work:
- if ```options.forceFitColumns``` is used, this should set the ```options.autosizeColsMode``` to ```Legacy``` automatically
- if  ```options.autosizeColsMode``` is ```Legacy``` then the autosize-after-column-resize behaviour should also be switched on (otherwise autosizing is only done on init or on explicit call to ```autosizeColumns()```
- you can pass an ```autosizeColsMode``` parameter to ```autosizeColumns()``` but if you don't it just falls back to ```options.autosizeColsMode```. So for legacy behaviour, you should just use ```options.forceFitColumns``` and call ```autosizeColumns()``` with no parameters

**Comment by ghiscoding** [comment]
@vrad-joshuamckelvey 
I think that @6pac already did all the code change, in this [commit](https://github.com/6pac/SlickGrid/commit/87db84f0c8d1e825f298efe607c3c43e23cd4cc3), that you mentioned in your original PR. If you see any missing change, you could let us know and we could fix them... oh and sorry we are kind of hijacking this issue to discuss our upcoming new release hehe

@6pac 
I never use the `forceFitColumns` because of it's side effect that it always resize other columns after a column, my users don't like this behavior as it confuses them, they don't understand why when they enlarge one, another get smaller. Anyhow, I always use the `autosizeColumns` and now I have to pass the Legacy to it for it to work like before. Using the `autosizeColumns` is a hack that I found, it's like using `forceFitColumns` but only once, then I'm never stuck with the side effect of the force fit. 

From what I see, there's only 1 issue #400 (last row cut off) reported since version `2.4.10` and I fixed that already (as mentioned in that issue). I would be ok to have a new version with the code we have now. I don't see any other issues

**Comment by 6pac** [comment]
OK, I've set up Legacy mode to mimic ```forceFitColumns``` now! So I'd better roll that back. Hopefully have a release in the next day or so. Over and out.

**Comment by ghiscoding** [comment]
@6pac 
From what I've tested, your code change of yesterday had no side effect compare to last week, or in other words, I didn't see any changes from the code of last week compare to yesterday's code. They both work, as long as I pass the Legacy as argument to the `autosizeColumns` (last week or yesterday, both need the argument).

**Comment by 6pac** [comment]
Ah yes, that's true as long as you don't set ```options.autosizeColsMode``` to Legacy, which is what ```forceFitColumns``` does. So I think we're good!  :-p

**Comment by ghiscoding** [comment]
You mean this [line](https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L2775) with that grid option? No I'm not using that and the `forceFitColumns` is disabled by default in my repo. I only leave this force fit option available from the ColumnPicker (also available in GridMenu since they both have same commands), just to do a quick resize to fit, but I re-disabled it right after. Should we remove the options from ColumnPicker and GridMenu then? It also has the syncResize which I never used, neither do I know what it does anyway.

**Pull request closed without merging**
