### PR TITLE
Changes to support jQuery 3

### PR DESCRIPTION
**Pull request by lfilho**
Hey @6pac, thanks for your work in keeping this.

This PR is a set of harmless changes in order to provide compatibility with jQuery 3.

The changes were based on running the jQuery Migration plugin for version 3. They are supposed to be harmless and were doubled checked by running the tests (nothing broke) and also did some basic manual testing.

For more details on each change see:
- https://jquery.com/upgrade-guide/3.0/
And more specifically:
- https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnandself-replaced-by-jqueryfnaddback
- https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryfnbind-is-deprecated

I also removed trailing whitespace, so feel free to [view the diff without whitespace diffs](https://github.com/6pac/SlickGrid/pull/39/files?w=1). Thanks

### CODE REVIEW

**Comment by lfilho** [comment]
@6pac hey 6pac, I understand this repo is not your top priority anymore but if you could review this & merge would be a huge win for all of us, otherwise we just can't use the lib with jquery >= 3 and I'm hoping we don't need to create another fork of SlickGrid just for that 😊 

Thanks a lot!!

**Comment by 6pac** [comment]
will do, sorry, i've been away on holiday. and also having a look at the new jquery 3 implications. just gotta do some regression testing with this and it's in.

**Comment by lfilho** [comment]
Great to hear back from you, @6pac. Alright, let me know if I could help in any other way

**Comment by lfilho** [comment]
Hey @6pac did you an opportunity to review this? Thanks

**Comment by 6pac** [comment]
sorry, not moving very fast recently. a month of school holidays just finished yesterday, so i now have my life back. i know you guys are keen, but i've been juggling a whole bunch of things. will get to it as soon as i can.

**Comment by lfilho** [comment]
Sure, thanks for getting back and doing your best. :)

**Comment by lfilho** [comment]
Hey @6pac, I'd just like to add that my company's QA team just tested our internal SlickGrid usage with my fork and everything seems to work fine... \o/

Did you have some time to test it like you wanted? Thx

**Comment by 6pac** [comment]
awesome. really sorry to be dragging the chain on this one, but i'm just really busy with work _and_ personal stuff right now. 
i will get to it.
but big thanks for your efforts, and they'll definitely end up part of this repo.

**Comment by lfilho** [comment]
No problems, dude! Thanks for your efforts as well (which were bigger than mine 😊 ). We're all just trying our best.

If it's not asking too much do have a rough estimation? Because depending on it my company will just have to fork this into its own organization instead of using this repo. Many thanks

**Comment by 6pac** [comment]
should be able to do this by the end of this week.

  _____

**Comment by 6pac** [comment]
So I have tested all the examples with jQuery 1.8.3, 1.11.2, 2.2.4, and 3.1.0.
Everything works EXCEPT ```example9-row-reordering``` under jQuery 3.1.0. 
I note that I also get an error message if ```jquery.event.drag-2.2.js``` (or ...drop..) is included, unless I include ```jquery-migrate-3.0.0.js``` as well. With jquery-migrate the errors disappear, but the above example does not work (no exceptions are thrown).

So this is clearly a problem with the drag and drop libraries. I've got another pull request from a contributor who has rewritten the code to remove the dependencies on these libraries, but is only compatible with jQuery 2+.
I will see if I can work out a patch for the libraries, but otherwise we may need to split off a new repo for drag & drop under jQuery 2+.

Any code or suggestions appreciated :-)

**Comment by 6pac** [comment]
I'm going to merge though, because the outcome is so much better than what i've got now.
Thanks so much for the contribution!

**Comment by lfilho** [comment]
I have just opened another PR for the jquery.event.drag lib: https://github.com/6pac/SlickGrid/pull/44

We also use it here so that's why I didn't see you were using it too: it's warnings from the jquery migrate plugin were solved by using my version of the same lib (which was already updated). :)

**Comment by lfilho** [comment]
Oh yeah! Thanks for merging this! =]

**Pull request merged**
