### PR TITLE
Added option to show/hide the "Force Fit Column" and the "Sync Resize" buttons

### PR DESCRIPTION
**Pull request by caroph**

### CODE REVIEW

**Comment by ghiscoding** [comment]
If I understand correctly, these options are simply to show/hide the "Force Fit Column" and the "Sync Resize" buttons, is that correct? If so, I like the idea, I rarely use these buttons and a way to hide them would be nice.

**Comment by caroph** [comment]
Yes, that's exactly, just show/hide the options

**Comment by ghiscoding** [comment]
@6pac looks good to me, I'll let you review it. Thanks

**Comment by ghiscoding** [comment]
@6pac can this PR be reviewed again? I also have grids which the users are getting confused with these 2 last checkbox options, I don't even know myself what the "Synchronous resize" button does!?

I'm also creating another PR to address the same for the Grid Menu (hamburger menu)

**Comment by 6pac** [comment]
Yeah, this is the one I looked at briefly and never got back to. I'll check it out this evening.

**Comment by ghiscoding** [comment]
The new PR #195 I created is for the Grid Menu and I changed the `disableForceFitButton` to `hideForceFitButton` as you suggested earlier. So for sure we have some changes to do in this PR here.

**Comment by ghiscoding** [comment]
Superseded by PR #197 which was merged. Thanks @caroph for the original PR.

**Pull request closed without merging**
