### PR TITLE
Change span to div. Insertion to html, to allow material icons support

### PR DESCRIPTION
**Pull request by aparmar**
Changing it to a div will support libraries like material-icons, framework7, etc

### CODE REVIEW

**Comment by ghiscoding** [comment]
I can already use Material Icons in Angular-Slickgrid as can be seen below and here's the [Example](https://ghiscoding.github.io/Angular-Slickgrid/#/tree-data-parent-child) that goes with it. In my lib I use the `::before` pseudo with `content` and it works well, even works with SVG using the same technique (with 1 small caviat that I can only assign the color of the icon once). I use the pseudo trick across the SlickGrid CSS and it serves me well, I'm able to change any icons I want, as long as I have a CSS class name, which the header menu does. Changing a `<span>` to a `<div>` possibly has big repercussion and will possibly introduce UI breakage for a few of us, though I must admit I haven't tried yet.

Also you're changing the `.text()` to `.html()` and this opens the door to potential XSS, this is a bit risky without using extra libraries like DOM Purify. 

So your PR might be small but I'm not sure I fully agree with it. 

image

**Comment by aparmar** [comment]
Ah...you did it in CSS. One of the nice parts of material icons is being able to use the <i> tags in line with the caption, as shown in the google example:

`<i class="material-icons orange600">face</i>`

Any thoughts on how I can achieve that? If not, I will plan to use the CSS workaround you suggested and withdraw the PR.

On the note about .html() being non-safe, I guess that is true. It comes down to the use-case - do we want the grid doing the sanitization, or do we want the developer using the grid to do the sanitization. Per the jQuery docs, append is non-safe as well. Both are being used in other places in slickgrid. I guess that can be removed in the future.

> By design, any jQuery constructor or method that accepts an HTML string — jQuery(), .append(), .after(), etc. — can potentially execute code. This can occur by injection of script tags or use of HTML attributes that execute code (for example, ). Do not use these methods to insert strings obtained from untrusted sources such as URL query parameters, cookies, or form inputs. Doing so can introduce cross-site-scripting (XSS) vulnerabilities. Remove or escape any user input before adding content to the document.

**Comment by ghiscoding** [comment]
You don't have to use `<i>` it's just a convention that is meant to represent icon but seriously you can use any tag you want, `<div>`, `<span>` whatever else, as long as you add a `class` it should work. 

> On the note about .html() being non-safe, I guess that is true. It comes down to the use-case - do we want the grid doing the sanitization, or do we want the developer using the grid to do the sanitization.

The thing is that we have the option to add an icon class, prior to the text, so I never really use anything else. Why would you want to add extra html? Does it ever happen that you need more than an (icon + text) combo? in my case, all of my sub-menu are exactly as shown in the print screen I've put earlier... so I'm just wondering when or why would you want more html than that? 

Also note that in my lib Angular-Slickgrid (a wrapper on top of SlickGrid), I do have a dependency of [DomPurify](https://github.com/cure53/DOMPurify) and I sanitize where I use `.html()` but typically in something outside of SlickGrid (in my case I use an extra 3rd party lib to build dropdown for Filters which have the option to pass html to each dropdown option and I sanitize it). Basically if you turn this from `.text()` to `.html()`, I'll have to sanitize it in Angular-Slickgrid because I don't like to have possible unsanitized section of the lib. SlickGrid however has do dependency on any sanitize lib so it's a possible door to XSS, but again when would you need html in the header menu when you already have a css class for the icon!?

**Comment by aparmar** [comment]
@ghiscoding I think we are in agreement. I initially needed the .html() so that the `<i>` tags would get processed, and the image shows up, when I passed them with the icon+caption in the title. With the css workaround you suggested, I can make it work for my use case. Therefore I can withdraw / close the PR.

**Comment by ghiscoding** [comment]
Glad you got it to work, SlickGrid is awesome 😉

**Pull request closed without merging**
