### PR TITLE
fix(ie): increase performance in IE, closes #367

### LINKED ISSUE #367: Performance in IE
We're using slick grid in an application with very wide data-sets, typically 150 columns and 100K+rows. We are updating from 2.3 to 2.4.7 and noticed a performance issue when using IE11.

The issue stems from the change in the cacheEntry node from a standard DOM object to a JQuery object which appears to have been introduced with the frozen columns updates. On testing the issue is only really prevalent with a large number of columns where not all columns fit within the viewport.

I've isolated two sections of code and applied changes below which has reduced the rendering time from 3 seconds + to 400ms in our application. Can you review and apply the same if there are no side effects.

Within the cleanUpAndRenderCells function

             /*
                Replaced below with DOM navigation to improve performance
            */
            var processedRow;
            var node;
            while ((processedRow = processedRows.pop()) != null) {
                cacheEntry = rowsCache[processedRow];
                var columnIdx;
                while ((columnIdx = cacheEntry.cellRenderQueue.pop()) != null) {
                    node = x.lastChild;

                    if (hasFrozenColumns() && (columnIdx > options.frozenColumn)) {
                        cacheEntry.rowNode[1].appendChild(node);
                    } else {
                        cacheEntry.rowNode[0].appendChild(node);
                    }

                    cacheEntry.cellNodesByColumnIdx[columnIdx] = $(node);
                }
            }

          /*
            var processedRow;
            var $node;
            while ((processedRow = processedRows.pop()) != null) {
            cacheEntry = rowsCache[processedRow];
            var columnIdx;
            while ((columnIdx = cacheEntry.cellRenderQueue.pop()) != null) {
                $node = $(x).children().last();
    
                if (hasFrozenColumns() && ( columnIdx > options.frozenColumn )) {
                $(cacheEntry.rowNode[1]).append($node);
                } else {
                $(cacheEntry.rowNode[0]).append($node);
                }
    
                cacheEntry.cellNodesByColumnIdx[columnIdx] = $node;
            }
            }
          */

The try catch within the getCellNode caused delays in IE when not all cells have been cached

        /*
            Replaced below with if condition to reduce error throws and improve performance
        */
        function getCellNode(row, cell) {
            if (rowsCache[row]) {
                ensureCellNodesInRowsCache(row);
                try {
                    if (rowsCache[row].cellNodesByColumnIdx.length > cell) {
                        return rowsCache[row].cellNodesByColumnIdx[cell][0];
                    }
                    else {
                        return null;
                    }
                } catch (e) {
                    return rowsCache[row].cellNodesByColumnIdx[cell];
                }
            }
            return null;
        }

        /*
        function getCellNode(row, cell) {
            if (rowsCache[row]) {
                ensureCellNodesInRowsCache(row);
                try {
                    return rowsCache[row].cellNodesByColumnIdx[cell][0];
                } catch (e) {
                    return rowsCache[row].cellNodesByColumnIdx[cell];
                }
            }
            return null;
        }
        */

### PR DESCRIPTION
**Pull request by ghiscoding**
- as per @secart suggestion

### CODE REVIEW

**Comment by ghiscoding** [comment]
I would like to have @secart review before merging, just to make sure I did the copy+paste of his code properly.

**Comment by 6pac** [comment]
looking great

**Comment by secart** [comment]
The changes look good. 

Longer term it would be good to revert to DOM objects in the cache instead of jQuery as this is also impacting the cleanUpCells function when removeChild is called. 

Thanks for following up.

**Comment by ghiscoding** [comment]
Thanks for confirming

@6pac 
Merge if you think this is good the way it is.

**Pull request merged**
