### PR TITLE
fix #371 for number larger than 2.14 billion

### LINKED ISSUE #371: getRowFromNode negative value when greater than 2147483647
We are using a provider model, similar to the remote model, with very large datasets. We recently ran into an issue where the data set is larger than the 32-bit int safe max value of 2,147,483,647.  When calling `getCellFromEvent` via a context menu click we are getting a negative number returned as the row.

Within [getRowFromNode](https://github.com/mleibman/SlickGrid/blob/master/slick.grid.js#L2395) it is currently returning a bitwise or operation to ensure that the value is an integer. When returning a number larger than the 32-bit safe int max it starts rolling into negative numbers. 

I've tested locally by changing the return value in `getRowFromNode` to return `return +row` without any noticeable bugs and returning the correct row number.

If you have any alternative ways to get the row from the context menu click, without going through the `getCellFromEvent`, we are open to hearing about it as well.

Thanks

### PR DESCRIPTION
**Pull request by vin-e**
Fixes issue (#371) with large numbers by removing the bitwise operation used on row index. I did not change bitwise operations done against column indices.

### CODE REVIEW

**Comment by 6pac** [comment]
Sorry, but I have to ask the obvious ... you have more than 2 billion rows?

Also, if you're going to go into the floating point numeric scope, you're going to have problems with precision: https://stackoverflow.com/questions/33773296/is-there-or-isnt-there-an-integer-type-in-javascript

**Comment by vin-e** [comment]
Thanks for the feedback and I will update the code as recommended.

Note, I took the path or using a `+` because there is a comment on line 3218 that reads: `// This is a string, so it needs to be cast back to a number.` My assumption was that we were validating the number.

To answer your other question... Yes, we have very large datasets with some reaching into the multiple billions. An internal user identified the bug when attempting to get the context menu on a row in the 5 billion range.

**Comment by vin-e** [comment]
FYI, The row is a string so we do need to parse the integer. Which is addressed on my latest commit.

**Comment by 6pac** [comment]
Awesome. Just trying to keep the code as bulletproof as possible!

**Pull request merged**
