### PR TITLE
feat(resizer): add optional grid container to resize

### PR DESCRIPTION
**Pull request by ghiscoding**
- optional but when provided it will be resized with same size as the grid (typically a container holding the grid and extra custom footer/pagination)

TODOs
- [x] manually tested in all my libs
- [x] manually tested with the `example15-auto-resize.html`

### CODE REVIEW

**Comment by ghiscoding** [comment]
@6pac 
Would you mind pushing a new version, I'm about to release my new lib [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal), probably early next week and this PR is something I'd like to be merged and released.

Cheers mate :)

**Comment by ghiscoding** [comment]
@6pac 
Sadly it seems my PR wasn't merged before you released your new version. I probably should have merged it myself 😢

**Comment by 6pac** [comment]
whoops! anything else you want in there?

BTW please do feel free merge your own PR's. On past history, I'm sure if there's anything controversial, you'll ping me.

**Comment by ghiscoding** [comment]
Yes I'll do that in the future, just a habit so that I like to advise you of a change... no that is all I needed. Thanks

**Comment by ghiscoding** [comment]
@6pac 
Thanks for the latest version, I just got my first and official release of [Slickgrid-Universal](https://github.com/ghiscoding/slickgrid-universal/releases/tag/v0.1.0) 🎉 🎉

**Comment by 6pac** [comment]
Congratuations! The next few months I'm having a slower time with work, so I'm hoping to have a chance to back-port some of your features to the base slickgrid. Looking forward to it!

**Comment by ghiscoding** [comment]
@6pac 
If you have free time and want to look at adding some feature(s), I might be interested in these Examples from the `GerHobbelt/SlickGrid` fork. I'm not sure if it's feasible with our fork since we now have the frozen feature, which I don't think GerHobbelt does, so it might or might not be doable, but it would be nice to have the following. I did not look at the code at all, I just clone his repo and looked at all the samples he has (a lot of them), these 2 picked my attention. 

- [example-0031-row-span.html](https://github.com/GerHobbelt/SlickGrid/blob/k0stya-rowspan/examples/example-0031-row-span.html)
- [example-0032-row-span-many-columns.html](https://github.com/GerHobbelt/SlickGrid/blob/k0stya-rowspan/examples/example-0032-row-span-many-columns.html)
image

- [example-0034-variable-row-height.html](https://github.com/GerHobbelt/SlickGrid/blob/k0stya-rowspan/examples/example-0034-variable-row-height.html)

image

### Side Note - Tree Data
On a Side Note, something that you won't have to port, I have a Tree Data Example [here](https://github.com/ghiscoding/SlickGrid/blob/master/examples/example-tree-data.html) in my own SlickGrid fork that I collaborated with another awesome person (Alex @alex-ley) that he's helping me with (or I should say, he did most of the work), it's not quite finish yet but that is something which is in my own libs and will eventually flow to your fork. You can see a live demo in my new lib `Slickgrid-Universal` [Tree Data with Parent/Child Ids](https://ghiscoding.github.io/slickgrid-universal/#/example05), [Tree Data with Hierarchical Dataset](https://ghiscoding.github.io/slickgrid-universal/#/example06), what's missing in these 2 demos, is that we'd like to eventually add the built-in SlickGrid Aggregators (sum, avg, ...) to this feature and if we can get that working then we'll push it to your fork afterward (though we don't have any timeline, possibly before Christmas, no rush... Alex will be a new father sometime this year 😉). 

We have a nice team, @6pac (Ben) is in Australia, @Alex-ley (Alex) is in Germany originally from UK and I'm in Canada, we cover a nice set of timezones haha. Cheers guys

The SlickGrid Example that will flow eventually to your fork through a PR will look like the following (it's already working for the most part).

image

**Comment by 6pac** [comment]
nice!

**Comment by Alex-ley** [comment]
Nice to meet you @6pac - as @ghiscoding said, I'll try to get those last couple items on the tree data closed out soon (next couple months) :) - currently a bit busy at work but should calm down in August.

**Comment by 6pac** [comment]
Great, yeah there have been quite a few requests for a tree feature over the years...

**Pull request merged**
