### PR TITLE
fix: remove debounce to avoid horizontal scroll slowness, fixes #789

### LINKED ISSUE #789: Progressively slower horizontal scrolling
When scrolling horizontally through a grid using shift + mousewheel, the scroll speed gets progressively slower the further I scroll.

Please take a look at the video I attached.

My physical scrolling speed stays the same but the further i scroll towards either end of the grid, the speed in the browser decreases.

https://github.com/6pac/SlickGrid/assets/92430777/e8a13863-61ba-493f-8178-fb96da048a28

This issue doesn't appear on any other scrollable html divs, so I think the issue is with slickgrid. The behavior is the same in firefox and chrome.

I'm using Slickgrid v3.0.4 and Chrome v114.0.5735.134

Unfortunately I have no clue which code is relevant to this issue. But if you have any ideas, I will provide whatever you need.

Thanks :)

Edit:
I noticed that in the ["Fill browser" example from mleibman](https://mleibman.github.io/SlickGrid/examples/example12-fillbrowser.html), the horizontal scrolling works well. 
But in [this repo's example](http://6pac.github.io/SlickGrid/examples/example12-fillbrowser.html), the horizontal scrolling seems to be disabled.

### PR DESCRIPTION
**Pull request by ghiscoding**
- this PR simply rolls back PR #722
- fixes #789

### CODE REVIEW

**Comment by ghiscoding** [comment]
@6pac it looks like you pushed a similar commit, but mine also removes the `debounce` method from the `slick.core.js` since we no longer need it

**Comment by 6pac** [comment]
Sorry, yes just trying to get this release sorted so I added the fix. I thought the debounce method was worth keeping though, there are scenarios where it could be useful. I might just release as is and we can remove the debounce in a future change.

**Comment by ghiscoding** [comment]
ok go ahead

**Comment by 6pac** [comment]
release done. sorry about that, should have posted here before I did the commit - I just thought I'd quickly commit it and push before anyone had a chance to do anything. I have a small window of opportunity.

**Pull request closed without merging**
