### PR TITLE
Updates to Autosize Code - fixes #688

### LINKED ISSUE #688: bug in getColAutosizeWidth when using data provider
When the `Slick.Grid` constructor `data` is set to a custom object (exposing `getItem(index)` and `getLength()` functions),

The code here:

https://github.com/6pac/SlickGrid/blob/master/slick.grid.js#L2468-L2477

is buggy because `rows` is first set to _an object_ `{ getItem: .., getLength: .. }` and so the following calls to `rows.slice` are invalid and throw 

> TypeError: rows.slice is not a function

### PR DESCRIPTION
**Pull request by 6pac**

### CODE REVIEW

**Comment by 6pac** [comment]
@Kofifus and @ghiscoding proposed changes to the columns autosize coding - bug fixes and enhancements to bring it up to date with my offline repo. Could you check with current codebase and issues before I merge

**Comment by kofifus** [comment]
Hi seems there have been further work on solving https://github.com/6pac/SlickGrid/issues/688 in a better way in this PR so I cannot comment

**Comment by 6pac** [comment]
> Hi seems there have been further work on solving #688 in a better way in this PR so I cannot comment

yes, this is a more complete solution. Could you test it with your code before I merge it? Just wanting to check I haven't broken anything by accident

**Comment by kofifus** [comment]
I moved on from that code ATM can try early next week ? prob best just merge if passed your tests

**Comment by ghiscoding** [comment]
@6pac I'm currently in vacations, I'm not using the code you have for column auto-width resize, I implemented my own which you can see in my [Resizer Service](https://github.com/ghiscoding/slickgrid-universal/blob/master/packages/common/src/services/resizer.service.ts#L384-L458), for it to work I had to make SlickGrid `reRenderColumns` method as public method in a PR a while ago, but apart from that there wasn't any other changes to the core required. However if I look at your code change, you changed a lot of things in the core, I didn't check but I'm afraid this might impact my own implementation, I would prefer to see your implementation done outside like I did if it would be possible, or else if you think that it shouldn't affect my code then I'll give that a try but I'm not sure when, maybe in a week or 2 max. You can see a live demo of my implementation in this Slickgrid-Universal [Example](https://ghiscoding.github.io/slickgrid-universal/#/example14)

**Comment by ghiscoding** [comment]
if there's any type of breaking changes then you could also wait for the next major, I think I still have about a month or so to work on that part. The more code you guys are doing, the more changes of conflicts with my current major branch, I'm also very close to say bye bye to jquery event drag library as well and I'm also not using anymore for the column resize, I got my own code now which works with touch as well with about 75 lines of code. So I just hope your PR here won't affect it too much and won't bring new challenge

**Comment by 6pac** [comment]
@ghiscoding good to know. OK, I'll hold off anything significant until then,. I'm 99% certain this PR would cause no issues for you whatsoever. All changes are to autosize code sections only.

**Comment by 6pac** [comment]
Description of PR:  
- add members to columnAutosizeDefaults object of Column object, and use them to store and save basic data when calculating autosizes
- improve autosize logic for empty or small columns
- add WidthEvalMode 'Auto' (uses optional Formatter.ReturnsTextOnly property as a hint to choose Canvas or HTML mode)
- changes to make autosize code handle non-array data

**Comment by ghiscoding** [comment]
@6pac 
I tried with 2 of my libs and indeed it doesn't seem to have any impact with my own column resize implementation so it should be ok to merge. Could you however hold on with large PR changes after this one since I'm working on the next major version and would prefer to avoid large PRs which might bring conflicts. I also intend to create a `next` branch which I will use to merge the major change PR so you that can test it and we can also use that `next` branch to bring in anything else that could be breaking change like that other old PR that was brought back up and once we're all happy then we could merge `next` into `master` and release 3.0 (I assume within a month, most probably 2-3 weeks from now and I'll send you an email regarding this)

**Comment by 6pac** [comment]
Great, I'll merge this then, it seems the easiest way forwards.

I have also been thinking about adding a dataprovider to the grid. I've had one in my personal branch for 5 of 6 years now. Perhaps that's something I could do after you're finished, for v3.0? Ok with that being a later version. I'll have to double check, but I think it's nonbreaking - everything just defaults back to legacy behaviour if a specific provider is not defined.
The provider is a standard set of methods to allow access to any data source interchangeably.

**Comment by ghiscoding** [comment]
> Great, I'll merge this then, it seems the easiest way forwards.
> 
> I have also been thinking about adding a dataprovider to the grid. I've had one in my personal branch for 5 of 6 years now. Perhaps that's something I could do after you're finished, for v3.0? Or OK with that being in a later version. I'll have to double check, but I think it's nonbreaking - everything just defaults back to legacy behaviour if a specific provider is not defined. The provider is a standard set of methods to allow access to any data source interchangeably.

Yeah you could add that to this `next` branch that I'm talking about, which I'll create once I'm ready to push my breaking code. The best is to make sure to merge everything you need into the master branch and then only after I can create the `next` to avoid conflicts as much as possible

**Pull request merged**
