### PR TITLE
appendCellHtml: allow function valued cssClass

### PR DESCRIPTION
**Pull request by do-**
Hello 6pac,

Let me propose a minor improvement to SlickGrid column definition: allowing function values for `cssClass` that provide computable UI options for individual cells.

This is useful for:
* displaying icons in a "Status" column based on the corresponding field value;
* colorizing "Gain/Loss" as green/red;
and so on.

Currently, such tasks are only achievable with `asyncPostRender`, that seems a bit too heavy.

### CODE REVIEW

**Comment by khamaniram** [comment]
I too needed this feature and ended up in writing exactly the same code.
it's very useful and I think should be approved.

**Comment by 6pac** [comment]
Just checking you guys are aware of the column ```formatter```?

**Comment by do-** [comment]
> Just checking you guys are aware of the column `formatter`?
> eg: http://6pac.github.io/SlickGrid/examples/example2-formatters.html

Sorry, I really wasn't aware of the _extended_ column formatter. 

Maybe it deserves a mention in API docs?

For now, the corresponding description at https://github.com/6pac/SlickGrid/wiki/Column-Options looks as if the `formatter` output should be plain text only. My bad, I didn't find the counter-example, but, as you see, I'm not the only one.

**Comment by 6pac** [comment]
Yeah, sorry, the docs are not great. I have very limited time.  A lot of the time I just add an example to demonstrate the feature. Feel free to document the extended formatter if you want, or I'll eventually get around to it...

**Comment by do-** [comment]
Thank you for your trust,

I've just corrected the following: https://github.com/6pac/SlickGrid/wiki/Column-Options/_compare/369c3f0b53577a4c28bf47be5cc8cafc2b62b34b...63d7279fd544432e013cfa59f47dea8a37675a59

**Comment by 6pac** [comment]
Thank you! This is a collaborative project, and developers who are new to Slickgrid are in the best position to give feedback and to know what should be in the docs. So if you want to contribute as you learn, please do...

**Pull request closed without merging**
