### PR TITLE
feat: add column `reorderable` option to optionally lock a column

### PR DESCRIPTION
**Pull request by ghiscoding**
- we can take advantage of SortableJS `filter` option which can be used to filter column header with a certain CSS class. When using `reorderable: false` on a column, SlickGrid will add configurable CSS class to the column header which will be filtered out by SortableJS hence locking the column from being reorderable
- new options available:
  - Column: `reorderable` (defaults to true)
  - Grid Option: `unorderableColumnCssClass` (defaults to "unorderable")
  - CSS/SASS variable for Alpine Theme: `$alpine-header-unorderable-bg-color` (replace `$` with `--` for CSS var)
- also referencing an old PR #64 that brought the original idea

#### ⚠️ Warnings
I did add and set `reorderable: false` to the following 3 plugins, they can all be overriden when instantiating the plugin via their respective options
- Checkbox Selector Column (Row Selection)
- Row Detail
- Row Move Manager

brave_RO4KUzXlJ7

### CODE REVIEW

**Comment by ghiscoding** [comment]
cc @6pac

**Comment by zewa666** [comment]
looking forward to this one. would make a great fit for the row based edit plugin to lock down the actions column in its place.

**Comment by 6pac** [comment]
I'm good with this but the issue has always been that if you can't drag a column to a place in the column list, you can drag another column to its left or right and eventually acheive the same thing. I don't care about that, but thought I should just point it out.

**Comment by ghiscoding** [comment]
I know that point and it is mentioned in the PR, this feature is mostly helpful when you use plugin like checkbox selector (row selection) in which you want to keep the checkboxes column as the first column in the grid

**Pull request merged**
