### PR TITLE
Fix options references

### PR DESCRIPTION
**Pull request by SatanEnglish**
Changed the options references to be internal.
This is to fix when there isn't an options at global variable level

This version includes @ghiscoding changes.

### CODE REVIEW

**Comment by ghiscoding** [comment]
@SatanEnglish so the other PR I made to fix your issue should be closed and replaced with your PR, is that it?

**Comment by SatanEnglish** [comment]
@ghiscoding 
Yer this one should fix both issues.

Sorry would of got this in when you mentioned it but was late on a Friday and I had to get home to the family.

**Comment by SatanEnglish** [comment]
Hmm ok I'll have another look at it. 
Now that I think about it I had the same issue and had to fix something elsewhere as well.
I'll have another look at it.

**Comment by SatanEnglish** [comment]
I'll try look when I get home.
Think this issue was due to a mission getUID call but I'll need to check through all my logs at work to figure it out.

Anyway leave it with me and i'll fix this when I can

**Comment by SatanEnglish** [comment]
@ghiscoding 
This issue seems to be there even if I revert back from **_options** to **options**
Also it's only on that one example so I'll try see if I can figure out the issue

**Comment by SatanEnglish** [comment]
@ghiscoding 
Spent 2 hours to find that example is missing the new CSS link...
<link rel="stylesheet" href="../controls/slick.columnpicker.css" type="text/css"/>

I've added to the branch now sure if I need to press some button to update the pull or what.

Please advise if I do thanks

**Comment by ghiscoding** [comment]
@SatanEnglish 
Thanks for finding the issue, I approved the changes after testing it. 

@6pac 
You can merge it now, I'm ok with the changes

**Pull request merged**
