### PR TITLE
Use text=auto for JS and HTML files

### PR DESCRIPTION
**Pull request by vlsi**
JS and HTML are text files, so they should be checked be CRLF for Windows and LF for Linux

slick.grid.js was in CRLF

### CODE REVIEW

**Comment by ghiscoding** [comment]
@vlsi 
I don't think we can merge your PR as is since you seem to be using different settings in your editor and the files are showing on GitHub as a full change. So basically we cannot see what you really changed. Can you please change your editor settings and make commit that only shows what you changed. Thanks

**Comment by vlsi** [comment]
> So basically we cannot see what you really changed

You can set `hide whitespace changes` in GitHub UI:

**Comment by ghiscoding** [comment]
Ah I didn't know that setting. As for the PR itself, I'll let @6pac decide

**Comment by 6pac** [comment]
I've always hesitated on whitespace changes, just because of the diff noise. It's been on my list of to-do's for v2.4. However I think on reflection, we can manage that. It's great to have the whitespace changes bundled as a single PR, that's as it should be. Thank you.

Now there's only the tab-vs-space inconsistencies!

**Pull request merged**
