### PR TITLE
feat: remove legacy TreeColumns code - now unused

### PR DESCRIPTION
**Pull request by 6pac**
Updated version: Remove legacy TreeColumns code

### CODE REVIEW

**Comment by 6pac** [comment]
hmmm ... impressive crash and burn for something that should be zero impact. trying to work out what's wrong here - all appears to be well on a browser.

**Comment by 6pac** [comment]
@ghiscoding yes, I'm aware that it came from the other repo, but as far as I can tell, it does nothing useful and it's unused anywhere in the project. And it's quite modular - there is literally zero impact from removing it. 

A lot of tests are failing, but there's no problems I can see with the examples that are failing, when I open them in a browser. I'm currently trying to get Cypress to work on my dev environment so I can try to repo the failure locally. Got past a startup failure, now stuck with localhost not responding.

**Comment by ghiscoding** [comment]
you need to run the test under localhost and for that you need to run `npm run serve`, the full instructions are shown on homepage [here](https://github.com/6pac/SlickGrid#e2e-tests-with-cypress)

**Comment by 6pac** [comment]
Oh, thanks! A bit embarrassing that I didn't look at that first!

**Comment by 6pac** [comment]
@ghiscoding OK, a typo fixed and a line of code I thought could be omitted couldn't be. Looks all good now! 

Pretty much all this code would never be called unless ```treeColumns.HasDepth``` was true, which it never was unless you specifically set up parent column references. So, zero impact unless you were using this feature which was undocumented and untested.

Will merge once you've had a look. Bonus is I learned how to use Cypress. It's quite impressive!

**Comment by ghiscoding** [comment]
awesome this is great, I'm currently in the middle of trying something else which I'm not sure if we should ship or not under v4.0. Could you tell me what you think in the new Discussion #776 that I just opened for this.

Give me couple of hours and I should be able to give it a try in my own libs and check all my Cypress tests as well. As you found out, having proper E2E tests with Cypress is a really great feature to have, it avoids breaking our lib 😉

**Comment by ghiscoding** [comment]
@6pac ok I tried it in my lib and all Cypress tests (500x of them) still pass, also tried a bit in the UI and it seems to work correctly. So I'm ok with you merging it :)

**Comment by ghiscoding** [comment]
@6pac could you go in the project setting and in the "General" config, click the following checkbox so that I won't have to go manually delete branches by hand every time

image

**Comment by 6pac** [comment]
Done

**Pull request merged**
