### PR TITLE
Fix issue with vertical scrollbar not going all the way down

### PR DESCRIPTION
**Pull request by connyekholm**
Our company use the slickgrid and we had an issue with the vertical scrollbar not going all the way down in some scenarios. There is a gap at the bottom and there is no way to drag the scrollbar all the way down. The horizontal scrollbar is visible and the fault is that the code does not acknowledge this. There is a line in the code that determines if the horizontal scrollbar is visible but this misses with one pixel. The changed formula uses greater than or equal instead of only greater than. I saw that this solution was proposed in a PR long time ago to mleibman:
https://github.com/mleibman/SlickGrid/pull/1030/files

### CODE REVIEW

**Comment by ghiscoding** [comment]
That seems to not change much on my side, so I guess it's ok
But your PR is very hard to review since you have put the auto-format on save, the entire file is being reformatted and it's hard to know what really changed (unless we click on "hide whitespace changes"). You might have to redo it without auto-format

**Comment by ghiscoding** [comment]
@6pac 
I'm ok with the change, it has no impact on my side.

**Comment by ghiscoding** [comment]
@6pac 
I'm ready for another release after merging this PR, got a few fixes done.

**Comment by 6pac** [comment]
OK, shall I do a release now?

**Comment by ghiscoding** [comment]
Yes that would be great, thanks mate

**Pull request merged**
