### PR TITLE
VSCode NPM Publish task

### PR DESCRIPTION
**Pull request by ghiscoding**
A simple Visual Studio Code (VSCode) task to make it easy to NPM publish.

### CODE REVIEW

**Comment by ghiscoding** [comment]
run_task
publish

**Comment by 6pac** [comment]
Thanks, but I meant the pipeline more generally. NPM is a one-liner.
When I publish, I have to:
- update the version stamp in slick.grid.js
- update the version stamp in package.json
- copy all files to the IO (live code) repo
- commit and push the main repo
- tag the release
- push the tags
- publish to NPM
- commit and push the IO repo

I think a bash script would be the easiest way to accomplish all of this. You could probably create a VS extension just to run the script.

**Comment by ghiscoding** [comment]
I would say the best would be to create a GulpJS script and add a Task in VSCode to run the script. I did most of what you want in 1 of my older lib `Angular-Validation`, you just need to defined a [gulpfile.js](https://github.com/ghiscoding/angular-validation/blob/master/gulpfile.js) and define a function per action that you want. Just take a look at my [gulpfile.js](https://github.com/ghiscoding/angular-validation/blob/master/gulpfile.js) for inspiration. I might help you on that later

**Comment by 6pac** [comment]
So can gulp commit and push Git repos? I always thought it was for the stuff the VS automatically does. So I maintain SlickGrid using command line Git and Notepad++. But for projects that *use* Slickgrid, I use Visual Studio 2017.

**Comment by ghiscoding** [comment]
Oh that part I would not be so sure about that, doing Git stuff usually requires interaction with it. What Gulp does is scripts, like updating your readme, copy files, update version stamp, ... most of the thins that you can do in script, you can do with Gulp

**Comment by ghiscoding** [comment]
You can also run Gulp from VS if you in stall the extension for it

**Comment by ghiscoding** [comment]
This NPM package [standard-version](https://www.npmjs.com/package/standard-version) might do a big part of what you mentioned in your list of things you would like automated. I'm setting it up in my repos, I'll see how it goes but it seems interesting and I created myself some VSCode Tasks to automate it even more. Here's the description of that package:
> Automatic versioning and CHANGELOG generation, using GitHub's squash button and conventional commit messages.

**Comment by 6pac** [comment]
Looks interesting! I got the automation to testing stage last weekend, but it doesn't do the changelog as well, that would be sweet.

**Comment by ghiscoding** [comment]
Were you testing your automation maybe this "standard-version" or is that really a new version of SlickGrid `2.3.15`? I'm asking because there's no tag on Github.

Do you till need a script for the copy of files? are they local copy? 
If it's local copy, I can do that easily with an NPM script. I can update this PR.

**Comment by 6pac** [comment]
Yes, I did release 2.3.14 but forgot to pull changes first, so then went ahead and released 2.3.15. I have finished the automation tool, but I think it goes way beyond what the NPM tool will do.
The one thing it doesn't do is add the release message, but I've got it to write the collection of commit messages to a text file, and I just need to add the release message manually, which is a good thing anyway.

Perhaps I'll integrate the NPM script in down the track, but I'm not feeling like jumping into NPM right now.

**Comment by ghiscoding** [comment]
ok this PR is probably not needed then is it?

**Comment by 6pac** [comment]
Yeah, thanks but I think there's too much GIT stuff to do in the release script to use NPM. At the moment it's all encapsulated in a .NET console project. Really Bash, SED and AWK would have been the tools of choice, but I just don't have time to learn yet another arcane series of languages/tools to update the version stamps in the various files.

**Pull request closed without merging**
