### PR TITLE
Accommodate string type numbers for MinAggregator & MaxAggregator

### PR DESCRIPTION
**Pull request by nickfogler**

### CODE REVIEW

**Comment by nickfogler** [comment]
> I think it's incorrect to use the parseFloat that way, since your cell value might be null in your dataset, and if that happens then the parseFloat will throw an error (I think).

The following might be better (do the parseFloat after you validated that it is a number). Could you test it with your use case? I didn't test it myself, thanks

`var val = item[this.field_];
      if (val != null && val !== "" && !isNaN(val)) {
        if (this.min_ == null || val < this.min_) {
-          this.min_ = val;
+          this.min_ = parseFloat(val);
        }
      }`

**Comment by nickfogler** [comment]
I need to change the val to a number prior to `val < this.min_` because comparing strings using the less than operator gives funky results (`'99' < '349'` is false, for example).

`parseFloat(null)` gives `NaN` so I think it's safe here.

**Comment by ghiscoding** [comment]
However the `SumAggregator` and `AvgAggregator` both have the `parseFloat()` inside the `if` as can be seen on [this line](https://github.com/nickfogler/SlickGrid/blob/57f63d1f7311143c7069d5d4e48fa3128bc10712/slick.dataview.js#L1132). The thing with having the parse on the first line is that there's 3 levels that can be undefined (previously 2 levels) and potentially throw an error (the worst piece is `item[this.field_]` as this can invalid). You're also hiding away the real value when it's not a number, instead of having  

You brought a good point though, you should probably add a `parseFloat` on the comparison too, to avoid comparing against string (when it's a string it uses ASCII code position for comparison and '9' is bigger ASCII than '1' so yeah '99' is bigger than '199').

How about something like this?
```diff
    this.accumulate = function (item) {
      var val = item[this.field_];
      if (val != null && val !== "" && !isNaN(val)) {
+       val = parseFloat(val)
-       if (this.min_ == null || val < this.min_) {
+       if (this.min_ == null || val < parseFloat(this.min_)) {
          this.min_ = val;
        }
      }
    };
```
You're probably going to say that the result will be the same, but somehow I feel it safer that way. Also if you're doing the `parseFloat` on the first line, you're hiding away the real value of it since it will become `NaN` instead of `null` or `undefined`, not much difference since it's an accumulator, but it's still better for troubleshooting.

@6pac what do you think?

**Comment by nickfogler** [comment]
Sure, that works for me!

**Comment by 6pac** [comment]
My apologies on this one also. I have toyed with doing things like this in the past, and it has inevitably bit me on the rear end later down the track.

The beauty of the aggregators as they are is that they are type-agnostic: put in an int, get out an int; put in a float, get out a float. Interfering with that by converting everything to a float can bring on rounding and formatting issues requiring manual conversion back to an int before using the total, or other workarounds that won't occur in the type agnostic version.

IMO the correct thing to do is to convert your underlying column data values to a float, if that's what they actually are.  
I appreciate that's not always possible, so as a fallback you might like to create a new Avg, Max, Min and Sum operator that do what you suggest and convert to a float - say AvgAsFloat, MaxAsFloat, MinAsFloat, SumAsFloat.  
However I'm not sure that they are necessary to add to the main repo, as I do regard them as a bit of a hack.

**Comment by 6pac** [comment]
I'm closing this, please ping back if you have anything further to add.

**Pull request closed without merging**
