### PR TITLE
Update event drag lib to be jQ 3 compatible

### PR DESCRIPTION
**Pull request by lfilho**
**NOTE**: please use the [`?w=1` option](https://github.com/6pac/SlickGrid/pull/44/files?w=1) to see the diff - lots of whitespace change (mixed and wrong indentation)

This removes the fixHooks part (supported by jq3 now) and updates the code to be jq3 compatible.

### CODE REVIEW

**Comment by 6pac** [comment]
Awesome! This fixes the row-reorder example. Is there any chance you could update the 'drop' lib as well? It's not used in that example enough to cause errors, but I can see 'bind' in there so it will cause trouble sooner or later. If that's done, I think all bases are covered.

Another thing I'll do is rename the drag and drop libraries so we don't get confused. I suppose I'll just bump the SemVer up and add some comments explaining the change.
So maybe ```jquery.event.drag-2.2.1.js```

**Comment by 6pac** [comment]
Actually I suppose the lib and also SlickGrid should probably go up a minor release version rather than a patch, since we are breaking support for jQuery 1.6 and earlier. It's also good to mark it as an important release.

**Comment by lfilho** [comment]
Hey man, I don't know why buy my company doesn't use the `drop` lib. I'll try to tackle this as soon as I have some free time (and then reinstal the jquery migration plugin, etc etc). But of course, if you want to do that before me, feel free 😄

**Comment by lfilho** [comment]
There you go man. I tested the aforementioned example and still works fine. But actually it didn't produce any output via jquery-migrate plugin... Maybe that `.bind` was never being executed...

There are some outputs more in the jquery-migrate plugin, but they're all coming from jquery-ui, so i'm afraid nothing we can do there (they shall release a compatible version soon enough).

I'll leave the SemVer dance with you, then. Probably better to do that outside of this PR.

Thanks again for the help

**Comment by lfilho** [comment]
Cool. Glad we did that collaboration. Could you please let me know here when you create the new tag? Thanks a lot

**Comment by 6pac** [comment]
yeah, thanks! that was a great contribution. It's updated and tagged. Got a little messy though (3 commits).

**Pull request merged**
