### PR TITLE
draggable-grouping

### PR DESCRIPTION
**Pull request by muthukumarse**
Updated example and added credit comments.

### CODE REVIEW

**Comment by muthukumarse** [comment]
@6pac -  Please review and proceed

**Comment by 6pac** [comment]
Looks good.   
The only thing is, I think the copyright and license thing might be going too far, it just complicates things from a legal standpoint, even though it's open source. I don't think I've even put myself in a license declaration anywhere!

Is it OK if we make it something like:

    

I'm just wanting to make sure that you are able to claim this as a significant enhancement to the project.
What do you think?

**Comment by muthukumarse** [comment]
Ok I agree. Please go ahead

Regards, Muthu

**Comment by 6pac** [comment]
there was a bug in the preHeaderRow code (option ```preHeaderPanelHeight``` was accidentally named ```preHeaderPanelRowHeight```). This was causing the viewport measurements to contain NaN which prevented any data from being displayed if the preHeader row was enabled..

Just fixed it. Please update to latest version.

**Comment by muthukumarse** [comment]
Thanks 

Regards, Muthu

**Pull request merged**
