### PR TITLE
feat(cypress): add Cypress E2E Grid Menu full test suite

### PR DESCRIPTION
**Pull request by ghiscoding**
This enhances previous basic test of the Grid Menu Example into a full test suite. Currently the last test will fail, because of issue #424, once that issue is fixed then the test should pass. See below for animated gif of the full test. To test it on your computer, you need NodeJS, then run the following 2 commands: `npm install` and then `npm run cypress:open` and finally click on the "Run all specs" button once the Cypress UI opens.

Also I removed the Cypress folder from the NPM package, it shouldn't be there on the final bits, it should only be in Git

@6pac 
If you have a chance, could try to install Cypress and see if you get the same result. This should help for future commits in the repo. 

image

mb5DrEsnCs

### CODE REVIEW

**Comment by 6pac** [comment]
Got it going, it's throwing a bunch of errors for me around the help menu, like the menu is closing before that step and it's assuming it's open. But Cypress is installed and running, looks very impressive. I'm going to a remote location for a month, so I may have time to check it out locally, but my internet may well be sketchy.

**Comment by ghiscoding** [comment]
@6pac 
I didn't try it out after your new release, I might have to tweak it, the last test was failing before the fix and I'm not sure if I coded the test correctly for it to work after the fix. Also worth to know, the test is against the GitHub Example page, so it might be slow. 

The next step will be to add [http-server](https://www.npmjs.com/package/http-server) for the tests to run locally. Add more tests and finally make it part of the build, in my repos I now use [CircleCI](https://circleci.com/) to automate my build process and every time I create a PR, the build and tests run. I hope we could implement it the same in your repo, that would avoid have breaking code PRs, or at least we would be informed about these breaking changes.

**Comment by 6pac** [comment]
Yep, local testing was on my mind too. I'm fine with implementing CircleCI, but also a little cautious - I was part of a project where I kept getting false test fails which ate up a lot of time trying to diagnose, and it turned out to be problems with arcane parts of the setup code.

**Comment by ghiscoding** [comment]
Well it's actually what I thought that was happening with version `2.4.12`, I assumed at first it was false positive then I realized it was actually something broken. So I prefer to have some kind of safety net in place that can catch something which we can choose to investigate or choose to disregard. I have both unit tests and E2E tests and when it's time for a major code refactoring, I'm no longer so concerned nowadays.

**Pull request merged**
