### PR TITLE
Update for NPM

### PR DESCRIPTION
**Pull request by at88mph**
Hi Ben,

Here is the latest.  Running `npm run package` will generate a minified version of the core functionality in the `dist` folder.  I've added javadocs where non existed before, and has been updated with  `6pac/master` as of July 14th, 2017.

There are many changes, many are new files, and many are the javadocs mentioned above.  I've started migrating test logic from the test directory into the NPM tests by extracting the test logic into shared files, which pass.

The `plugins` and `controls` items have their own NPM build files, too, which can be used to create NodeJS-ified outputs.

I'm happy to keep working on this.  I am new to NodeJS as well, but I really like the idea of bundling very useful libraries and applications together.  My use case involves displaying large rows of search results from astronomical data, so I extend SlickGrid with some query infrastructure, and it would be great to simplify that style, although I suspect many use cases involve just using the Grid directly.

There are some TODO items:
  - How to migrate the `controls` and `plugins` items into deployments and distribution?  Should they be individually published and pulled in as requested?  Should there exist a monolithic SlickGrid?
  - Work to migrate all tests to ensure what NPM builds is correct.  Is this necessary or is NPM just a delivery mechanism and these tests are just redundant.
  - jQuery updates?  Move away from jQuery-UI?  It has known issues with NodeJS.
  - Anything else that can be discussed here.

### CODE REVIEW

**Comment by azz** [comment]
What is `dd` on https://github.com/6pac/SlickGrid/pull/132/files#diff-d16bb972eb75f2be965a64ebbf27feccR46?

**Comment by at88mph** [comment]
The method arguments?  I’m pretty sure it’s event data, or an object with even data in it.  It was unused in those cases.




Dustin N. Jenkins 
Tel/Tél: 250.363.3101 | Mobile: 250.217.4970 | Facsimile/télécopieur: 250.363.0045 | Dustin.Jenkins@nrc-cnrc.gc.ca 
National Research Council Canada | 5071 West Saanich Rd, Victoria BC. V9E 2E7 
Conseil national de recherches Canada | 5071, ch. West Saanich, Victoria (C.-B) V9E 2E7 
Government of Canada | Gouvernement du Canada

**Comment by piyushgupta1** [comment]
@at88mph @6pac Does this build have issues or it can be merged in master? As right now without a proper npm or es6 version integrating is a pain.

**Comment by 6pac** [comment]
@piyushgupta1 The honest answer is that I don't know. This PR has thousands of lines of code. I'm very hesitant to pull PRs even with twenty lines, without good testing. PRs need to be segregated very carefully into functional units - that is, changes for one feature are not to be mixed with another.

So, I would dearly love someone to make this Node compatible, but I don't use Node, so I have no idea what the good practices are. The main issues I'm looking for are:
- ONLY node related changes in a PR
- the changes must have no impact on non-node users, or must involve some (hopefully elegant) way of maintaining coexisting alternate versions
- consensus from some people I trust that this is a PR containing best-practice code

I trust people who I have seen do PRs in a way that shows they understand, or are willing to discuss and understand, the principles involved in PRs and user interface design and versioning. 
Some people submit PRs that are meticulously well thought out and thorough, other people dump very poor quality code in there expecting it to be pulled, and everything in between.
I have to navigate the risks of destabilisation of the code base versus integrating possibly valuable contributions.

**Comment by at88mph** [comment]
This pull request is incomplete, quite frankly.  The items in `controls` and `plugins` are not integrated as I wasn't sure if they should be externally created as a Node package or somehow imported into one monolithic product.

I really want this feature and I agree someone with good experience with Node development should weigh in.  Ideally the core code is left alone and NPM just wraps it somehow.  I hope that's easily done, and I'm still working on it.

**Comment by 6pac** [comment]
Thanks Dustin. I understand the issues with wrapping anything with plugins ... it's not straightforward, and there's More Than One Way To Do It (TM). I really want this feature too. Surely there's a Node guru out there somewhere!

**Comment by ghiscoding** [comment]
I would suggest to add a `src` and `dist` folders to hold these new files. I know it would duplicate the files, but this way, we could start using it with true NPM (import/require) from the `dist` folder and provide feedback on them while still having the regular files in the root for reference (until we can say it's all good, which at that time we could delete the non-NPM files in the foreseeable future). 

As for the `controls` and `plugins`, I like the way that is used in the [SlickGrid-ES6](https://github.com/DimitarChristoff/slickgrid-es6/tree/master/plugins) package. Having an index.(js|ts) that holds the list of the exported plugins/controls is great and easy to use.

**Comment by 6pac** [comment]
Sounds good. I currently have a 'npm' folder with three files in it, I'll try to work out how best to make it fit in with what you are proposing.

**Comment by piyushgupta1** [comment]
@6pac @ghiscoding @at88mph i dont have much experience in Nodejs but i am currently working in angular + typescript. I live the approach google has taken with angular packages. The provide Flat es5 js files for all there components. I agree that having small files will clearly help in tree shaking and uglify but having a monolithic file with all components also work well for some projects

**Pull request closed without merging**
