### PR TITLE
Fix sorting after hiding a column when "multiColumnSort" = true

### PR DESCRIPTION
**Pull request by levushka**
When when "multiColumnSort" = true, and you provide multiple sorting columns.
After hiding not sorted column. The error will rise after 3-4 sorts on same column by headerMenuPlugin.onCommand

### CODE REVIEW

**Comment by ghiscoding** [comment]
It looks like you are using different indentation and it's make it hard to see the changes. Could you use the same indentation? I think it's 2 spaces for indentation (or 4 but it's definitely not a Tab)

**Comment by 6pac** [comment]
Whoops, I approved #293, was this meant to be instead of that pull?

**Comment by levushka** [comment]
Hi, sorry for the  indentation, I just used Git Web interface, to commit my
request.

293 & 294 they a different, for different issues.

**Comment by ghiscoding** [comment]
@levushka 
I tried your code and even if it would be nice because it looks simpler, it actually doesn't work and throws some error in the console when trying to sort by the header menu

```js
example-plugin-headermenu.html:143 Uncaught TypeError: Cannot read property 'field' of undefined
    at example-plugin-headermenu.html:143
    at Array.sort (<anonymous>)
```
So we cannot merge this code as it is, you will have to fix it first.

**Comment by 6pac** [comment]
Rather than pull this, I elected to completely rewrite this example page. There were a number of additional subtle bugs needing fixing and the new code greatly simplifies the logic required.

**Pull request closed without merging**
