### PR TITLE
Fix for text selection in firefox

### PR DESCRIPTION
**Pull request by inkonito**
There is an issue on firefox browser that prevent the user from making a selection.
This issue is already fixed in the original repository.
See https://github.com/mleibman/SlickGrid/pull/746/files

### CODE REVIEW

**Comment by 6pac** [comment]
Happy to patch, but can you confirm that this is still an issue in the latest Firefox, and describe a test case (eg. step by step actions to reproduce)?

**Comment by inkonito** [comment]
Hello,

Thanks for the fast answer.

The issue is still occuring in Firefox 83.0. 
To reproduce, open any grid on Firefox, and try to select any text inside a cell with the mouse.
Once you release the mouse button, the selected text is deselected.

**Comment by 6pac** [comment]
So here's my test. Chrome is at the top, Firefox at the bottom. This is on my test Windows 7 VM. I can't select anything in the basic grid on either (you can see me dragging), and in the editable grid, selection works identically on both.  
This appears to be different to what you're getting. Can you elaborate? I used ScreenToGif to create this.


TextSelect

**Comment by ghiscoding** [comment]
I remember this always being a problem and that is mainly why I added a "Copy Cell" in a Context Menu in the [Example - Context Menu](http://6pac.github.io/SlickGrid/examples/example-plugin-contextmenu.html), unless of course the user wants to copy multiple cells, but if I remember correctly, wasn't there also a CSS change that needs to be changed to unblock the selection? 

image

**Comment by inkonito** [comment]
I was able to reproduce on the link that @ghiscoding sent.
Here is a capture with the first tab with the current slickgrid, and second tab with my pull request:
slickgrid

I did not know that the selection was prevented on some grids. Anyway, for the project i'm working on, selection is not prevented, and users want to copy many cells to paste into excel (yes, i know...).

**Comment by ghiscoding** [comment]
The most effective way to copy data is to use the external copy manager plugin as demoed in this [Example- Excel Copy](http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet.html)

From your last animated gif it looks like there's no issue, so I wonder what this PR will bring?

**Comment by inkonito** [comment]
I do not agree with that.

As you can see in my gif, in the first tab, as soon as i release the mouse button, the texte is deselected. On the second tab, after releasing the mouse button, the text remains selected. 

I'll look into the copy manager plugin, but i still think that is not a normal behavior for text selection in firefox.

**Comment by 6pac** [comment]
OK, I can see the issue now. I'm having some dramas with my hardware right now, so it might be a few more days until I can review it properly - I installed Firefox on a text VM but that's temporarily unavailable.

**Comment by 6pac** [comment]
Hey @ghiscoding just wanted to check with you - the link in the OP (https://github.com/mleibman/SlickGrid/pull/746/files) has you in the conversation, but it appears that the changes you thanked the person for aren't in the grid now? Just wondering if they got accidentally lost. In this case this PR should replace that code.

**Comment by ghiscoding** [comment]
@6pac just resuming after vacations... if anything was removed then I guess it would have been when doing the big Frozen feature merge and if anything is missing then it's probably better to put back those missing lines indeed.

**Comment by ghiscoding** [comment]
@6pac 
I forgot about this one, I think we should merge this since it does seem to be code missing compare to original SlickGrid (it probably got deleted when we merge the Frozen feature). I can fix the conflict but in order to do that directly from the browser it asks me if I want to merge to `master` branch, so are you ok with this PR then? If so, I'll fix the conflict and merge to `master`, let me know if that's ok

**Comment by 6pac** [comment]
Sure, I'm fine with that. Thanks.

**Pull request merged**
