### PR TITLE
Fixed an issue where pinning the first column caused the header to get misaligned

### PR DESCRIPTION
**Pull request by songyuchen415**
https://github.com/6pac/SlickGrid/issues/1038#issuecomment-2246829300

### CODE REVIEW

**Comment by ghiscoding** [comment]
@songyuchen415 so does this fix your number 3 and 4 from your [comment](https://github.com/6pac/SlickGrid/issues/1038#issuecomment-2246829300)?

**Comment by songyuchen415** [comment]
@ghiscoding yes

**Comment by ghiscoding** [comment]
great thanks

**Comment by ghiscoding** [comment]
The fix is available in the new [v5.11.0](https://github.com/6pac/SlickGrid/releases/tag/5.11.0) release which also contain a new feature. Thanks for the contribution

**Pull request merged**
