### PR TITLE
feat(editor): add more functionalities to Composite Editor

### PR DESCRIPTION
**Pull request by ghiscoding**
This is a much more improved version of the Composite Editor, it adds the following
- validation error displayed in the form instead of being handled after the modal is closed
- made Editor LongText also work in the modal 
  - when it's Composite it uses a `relative` positioning
  - on regular cell editing, we still use `absolute` and re-position to cell position
- add header title
- fixed a few UX problems from previous `example-composite-editor-item-details.html`

### Recap
Quick recap, this PR adds the following 4 options all available from the Composite Editor Modal 
1. Edit Current Item (already existed, but improved a lot)
2. Create New Item (new)
3. Mass Update (new)
4. Mass Selection Change (new)

### TODOs
- [x] working code and example
- [x] add `invalid` class also to the input+label so it could be styled too (possibly change invalid input label to red)
- [x] add new Slick Event `onCompositeEditorChange` to know when an editor input changed, we could also add extra logic in the modal form with this 
  - [x] add validation logic to Example, when user checks "Effort Driven" then a "Duration" must be at minimum 5 days.
- [x] add option to "Add New Row" from the Composite Editor Modal 
- [x] add option to do "Mass Update" from the Composite Editor Modal
- [x] add option to do "Mass Selection Change" from the Composite Editor Modal
- [x] confirm with @6pac if we keep old file or not (see below)
- [x] add Cypress E2E tests

@6pac 
The file `slick.compositeeditor.js` already existed but it was under the `examples/` folder which its content is completely omited in the NPM release so from that location it's not available in my libs (hence why I create one in the root instead). I was thinking to leave that old file there and untouched not to break anyone's code but I wonder if that will create more confusion? What are your thought on this? Just to rephrase, in this PR we now have
1. `slick.compositeeditor.js` (in the root, new version)
2. `examples/slick.compositeeditor.js` (old version) --> this file is not visible from NPM since `examples/` folder is not included 

Should we keep both file or delete old one? The new file should is cross compatible, it doesn't break anything, it just adds a lot more functionalities to the composite editor modal, the question is just do we keep the old file or we simply remove it and have both Examples point the new file I created?

Sample Demo
VDDHEUGQvf

Also in my own lib it looks like this, it uses the same code, the only difference is the styling 😄 

image

### CODE REVIEW

**Comment by ghiscoding** [comment]
@6pac 
When you have a chance, if you could answer the question I wrote on top. 
I'm nearly done with the PR, just left with adding Cypress E2E tests

Things to note, it adds 1 new Slick Grid event `onCompositeEditorChange` in the core and it also adds a few changes into the `slick.editor.js` for all of this PR to be doable. 

See animated gif for what it brings to the table... we will use this in my work project.

**Comment by 6pac** [comment]
Sure, I think let's just use the newer version. No real advantage to saying with the old, and it will cause confusion.

**Comment by ghiscoding** [comment]
@6pac 
Thanks, that is the same thought I had on the matter. 

I'm just left with adding Cypress E2E tests, should I merge once I'm done (possibly by the week end)? 
You could always take a quick look at the changes
Also note that once I'm done, I'll be requesting another version ;)

**Comment by ghiscoding** [comment]
@6pac 
I'm facing a little problem to complete the PR (or actually I found a way to improve the UI), in order for me to do a "Mass Update" or "Mass Selection Change" action, I need to scroll completely at the end of the grid and activate that row with `setActiveCell(row, cell)` because the Composite Editor (modal) requires a row with an item at all time, by going on the last row 
 I'm able to start with a blank item (because I use `addNewRow: true`) and that works fine however this also have the side effect of scrolling to the last row and then going back to my original scroll position which is not exactly great UI/UX... so I'm proposing a new method `setActiveRow(row, cell, suppressScrollIntoView)` and for my use case I would pass the 3rd argument as `true` to `suppressScrollIntoView` which would, behind the scene, make the last row as the active row BUT it won't scroll to it (active row but without necessarily being in the viewport, which is exactly what I want)

```diff
+ function setActiveRow(row, cell, suppressScrollIntoView) {
+      activeRow = row;
+      if (!suppressScrollIntoView) {
+        scrollCellIntoView(row, cell, false);
+      }
+    }
```

Would you be ok with that new method? 
See the 2 animated gif (before/after) to see what I mean

without the new method, you can see once I click on the "Mass Update" or "Mass Selection Change"
RwsPsIFOBi

**with** the new method, activate the last **without** scrolling to the row (behind the scene, the last row is selected, it's just not into the view which is exactly what I want).
09JRktm6FN

**Comment by ghiscoding** [comment]
@6pac 
I'm done with the PR, should I merge it myself or do you want to have a final look at it? 
If you merge it yourself, then please use the "Squash and Merge" to merge it into 1 commit instead of multiple commits.

Also if you could release a new version but only **after** the merge (we wouldn't want 2 releases this time 😉)

**Comment by ghiscoding** [comment]
Wow that was quick 😉 
You can do the release in the coming days, no rush on that, it's a long weekend for us (Labor Day Holiday).

**Comment by 6pac** [comment]
Too late, it's done! Saturday morning here, just sat down at my computer to do a few other things. Good timing!

**Comment by 6pac** [comment]
Each time I release, I get this dependabot notification. I think it's because I am overwriting my package.json with yours, which doesn't have the patch. I have sent you the link, but it looks like you are prevented from viewing the page.
I'll paste below:

This automated pull request fixes a security vulnerability (low severity). 
Learn more about Dependabot security updates. 

--------------------------------------------------------------------------------

Bumps lodash from 4.17.15 to 4.17.20.

Commits 
ded9bc6 Bump to v4.17.20. 
63150ef Documentation fixes. 
00f0f62 test.js: Remove trailing comma. 
846e434 Temporarily use a custom fork of lodash-cli. 
5d046f3 Re-enable Travis tests on 4.17 branch. 
aa816b3 Remove /npm-package. 
d7fbc52 Bump to v4.17.19 
2e1c0f2 Add npm-package 
1b6c282 Bump to v4.17.18 
a370ac8 Bump to v4.17.17 
Additional commits viewable in compare view 
Maintainer changes 
This version was pushed to npm by bnjmnt4n, a new releaser for lodash since your current version.

**Comment by ghiscoding** [comment]
Haha awesome thanks mate... by the way, this new feature will be used and seen by apparently 10,000 users (customers as well) from what they told me. Doing a big push for SlickGrid within my company, you might know them, they have offices across the world included Australia, "Schneider Electric"


for the Dependabot, do you have any buttons to do the update or are they just notifications? The thing is `lodash` is not a direct dependency in SlickGrid, it seems like an indirect dependency.

**Comment by 6pac** [comment]
Great! I know Schneider quite well, I used to work for a company called Integrated Switchgear and Systems in Darwin, who were a major Schneider supplier for the NT, particularly to the massive Nabalco mine in Arnhem Land.

I think I've sorted out the dependabot stuff, firstly it was private to me, then it was applying the changes to 6pac.github.io rather than the main repo, so it was being overwritten on each release. If you can pull from the repo, there's an updated package.lock.

**Comment by ghiscoding** [comment]
Yeah Schneider is quite big, in fact I came to them indirectly since I used to work for a small local company (80 employees) which got bought by them 9 years ago and it's quite a difference and challenging working for a bigger company but I think I left a good impression since I'm still with them hehe. I've been pushing SlickGrid for a while and it got more attention last year after merging Canada/US/Mexico teams, I'm in the Salesforce world since the Sprint and found they pay an enormous yearly fee for another grid in Salesforce which is lagging so much behind SlickGrid in terms of UI and features (probably because I added so many plugins in the past couple years, lol) hence why you see me putting so much effort lately, though I think SlickGrid is becoming a lot more stable since we fixed a few issues over the years. 

The `package-lock.json` gets changed after doing an `npm install` on your local, if there's any differences after running it you will see the file as a code change. In the last PR, I've update Cypress to the latest version and that is why it pushed an updated version of the `package-lock`, which is a required file by the GitHub Actions, they don't seem to work without it. I could get your last commit and see if there's any changes or you could run it on your local, either or would work and should return the same result... and I just pulled your last commit, re-install with `npm install` and it shows me no changes, so I guess we're good.

**Comment by 6pac** [comment]
The SalesForce angle is interesting. If it turns out that there are some resources available for development, I do have several reasonably substantial changes that I'd be keen to implement - I just don't have the resources at the moment. 

For example, a data provider API (I have this in my personal grid, it would just need porting over - and it defaults to the current behaviour).
Another is rewriting the pinned column code to abstract out a virtual row/column model to make it look to the grid like there is a single viewport. This would (1) allow the grid code to be separated from the multiple viewports code, (2) allow more splits to be added without modifying grid code (eg. left and right splits, top and bottom splits - this would require 9 viewports), and (3) allow the max number of viewports to be determined by a plugin, meaning that where no splitting was needed, a single viewport could be used by applying a single-viewport plugin, resulting in simplifying the html and code, providing debugging and performance benefits.

That said, I'm still in the process of trying to fund my startup, which will complete directly with SalesForce. I took on SlickGrid specifically as a component of the startup project.

**Comment by ghiscoding** [comment]
The multiple viewports is an interesting topic, I remember you talked about that subject in an old issue. The frozen grid is great but it comes with its own problem, being 2 separate divs isn't always good to work with. 

I'm not a particular fan of Salesforce seriously, I find them a bit behind and playing catch up in certain areas. Mainly work with it because I don't have much other choices at the moment but that's ok I can push SlickGrid in the picture and make the company save money. At the end of the day, most enterprise require data grids and I'm getting good at working with them. 

Hope you'll get your startup going, I assume it's nice to be on your own but is also challenging.

**Pull request merged**
