### PR TITLE
fix(rowDetail): work with DataView custom "id" property name, fixes #420

### LINKED ISSUE #420: RowDetailView does not implement alternate IDs from DataView
The RowDetailView plugin does not correctly function if there is an alternate ID specified on the dataView when the items are set. See the following:

```
const dataView = new Slick.Data.DataView(dataViewOpts);
dataView.beginUpdate();
dataView.setItems(items, 'guid');
dataView.endUpdate();

detailView = new Slick.Plugins.RowDetailView(detailViewOpts);
```

On attempting to open a detail row, the error `Each data element must implement a unique 'id' property` is thrown.

### PR DESCRIPTION
**Pull request by ghiscoding**
- added a new `getIdPropertyName()` method to pull current "id" property name used in the DataView, this is required for external plugin to know what it is without specifically asking the user to pass it to every plugin
- added a new Slick  Event `onSetItemsCalled` in DataView to know when the DataView was last called, only then we know the "id" property name
- fixes #420

### CODE REVIEW

**Comment by ghiscoding** [comment]
@6pac 
I'm done with my local tests, I could have merged it myself since it's Row Detail plugin but just wanted to make you aware of the changes since there are 2 small changes in the DataView file.

Side note, I saw you gave me access to your other private project. Did you want me to test anything from there? I guess you could open an issue there to talk about it or email me  gbeaulac[at]gmail

Cheers

**Comment by 6pac** [comment]
Your testing is probably better than mine! 

The other private project is the 'FlexTable' which is what I use instead of DataView. For example, one small feature, it has no dependency on any unique ID column at all, it just uses row index to keep track of things. There's reasonably comprehensive docs in a folder in the project. Just interested in your feedback.  My private fork of Slickgrid has a DataProvider interface that will allow an object, a DataView or a FlexTable (or any other data provider that uses the interface) to be plugged in. It also contains a FlextableAdapter object that mediates the needs of the Slickgrid and the Flextable re refreshing and row management (DataView is more tightly bound to SlickGrid's way of doing things, FlexTable avoids that in favour of a simpler and more universal approach).

**Comment by ghiscoding** [comment]
Wow that is highly customizable, is it better on the performance side of it compare to the dataview?

**Comment by 6pac** [comment]
Arguably, because it supports two data formats, array based and dictionary based. Array based is significantly more efficient in both speed and storage. DataView only supports dictionary based.
There's a lot of overview in the docs, did you read them yet? It does everything DataView does plus a whole lot more.

**Comment by 6pac** [comment]
The idea is that it scales up, starting from bare-metal (really fast) and adding only features you need through lazy loading.

**Comment by ghiscoding** [comment]
I looked at what FlexData was when you gave me access but not more than that, I've been busy with so much stuff and now I'm starting new learning and new side projects, time is always an issue.

**Comment by 6pac** [comment]
Yeah, totally understand. It's the same here, flat out just keeping up with work...

**Pull request merged**
