### PR TITLE
Draggable Grouping - enhancement

### PR DESCRIPTION
**Pull request by muthukumarse**
this is same as - #210

### CODE REVIEW

**Comment by muthukumarse** [comment]
@6pac @ghiscoding  please look into it 

Cheers

**Comment by ghiscoding** [comment]
Just giving it a quick try and the first thing that comes up is that the groups don't do anything while clicking on the +/- icons.

**Comment by muthukumarse** [comment]
@ghiscoding - I agree. updated the sample to work both ways

**Comment by ghiscoding** [comment]
Thanks that's already better, another comment. I dragged 2 columns and I somehow found out that I can drag the 2nd column in the position of the 1st column to change the grouping (nice), however for that to work I need to hold the left mouse click, if I don't the column grouping is deleted. So what I found out is that the delete is actually on the entire column, while it should be **only** on the "X" icon. Also, could you add the `cursor: pointer` to the column titles that are in that draggable area, it would be easier to notice we can do something with them.

**Comment by muthukumarse** [comment]
@ghiscoding - patched as you suggested. please have look

**Comment by ghiscoding** [comment]
Nice, already much more usable, can you also please add the source link in the "Demonstrates" section. You can add this code 
```html
<h2>View Source:</h2>
<ul>
    <li><A href="https://github.com/6pac/SlickGrid/blob/master/examples/example-draggable-grouping.html" target="_sourcewindow"> View the source for this example on Github</a></li>
</ul>
```
just after this [line](https://github.com/muthukumarse/SlickGrid/blob/525a1a977181e60de37582f27234f3f8aad6dde6/examples/example-draggable-grouping.html#L82)

Another comment, if possible since it's more of a customization.
1. It would be nice to have an option to choose between an icon image or icon CSS class, like in this other [Header Menu plugin](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.headermenu.js#L52) where you choose between an `iconCssClass` or `iconImage`. The main reason for this in my case is that I use `Font-Awesome` which uses CSS classes.
2. Is it also possibly to show all options as javadoc, again like that other [Header Menu plugin](https://github.com/6pac/SlickGrid/blob/master/plugins/slick.headermenu.js#L47)

**Comment by muthukumarse** [comment]
@ghiscoding - added as you suggested. have look into it.

Cheers 👍

**Comment by ghiscoding** [comment]
@muthukumarse 
This is really great, though I'm so sorry I forgot to mention
1. both images (delete & drag icons) should have that CSS/image option. The drag icon should be optional too, not everyone would want it (especially if there's no space to put it when too many columns)
2. Would it be possible also to be able to pass the text of "Drop a column header..." as an option as well, so user can support multiple language (i18n). You can see an example[here](https://github.com/6pac/SlickGrid/blob/master/controls/slick.columnpicker.js#L42) and [here](https://github.com/6pac/SlickGrid/blob/master/controls/slick.columnpicker.js#L112)

This is the last thing that I'm requesting. 
Your plugin is really awesome, I'm planning on using it very soon. Thank you

**Comment by ghiscoding** [comment]
@muthukumarse 
Awesome I love it. Thanks for the excellent and quick work.

@6pac 
I'm done with my review, everything I asked was implemented :)

**Comment by muthukumarse** [comment]
@ghiscoding - Thanks for your input. Cheers 👍
@6pac - have look into it

**Comment by ghiscoding** [comment]
possibly blocked by issue #215

**Comment by muthukumarse** [comment]
@ghiscoding - getHeaderColumn - i fixed as part of this feature ( it was bug )

getHeaderRowColumn - don't see the usage across our example.

getFooterRowColumn - usage from example-footer-totals.html - working as expected

**Comment by muthukumarse** [comment]
@6pac @ghiscoding - looks like the changes not in master.

**Comment by ghiscoding** [comment]
I see it in `master`, however there won't be a new release until @6pac is ready for a new one (it could be in a few days or in a week). 

Please be patient. Thanks

**Comment by muthukumarse** [comment]
Noted 👍

**Pull request merged**
