### PR TITLE
Changed signature of sortedUpdateItem() to be the same as updateItem().

### PR DESCRIPTION
**Pull request by tatsujin1**
Also moved the sorted* functions a bit later in the code and a teensy-weensy bit of formatting.

### CODE REVIEW

**Comment by ghiscoding** [comment]
Thanks for your contribution, however I don't your code will be merged as it is now since it will most probably break someones code. I totally understand that you/we wish to be consistent in function naming and arguments, however we want to avoid as much as possible breaking peoples code.

**Comment by tatsujin1** [comment]
Too bad this wasn't merged earlier; when I submitted this PR, the sortedUpdateItem() function was only 2 days old.

**Comment by 6pac** [comment]
I'll go back and check. I may have made this change in the code anyway. Or if it's recent, probably not too bad to change it. Stuff is so badly documented at the moment, I don't think anyone knows most of the new features are even there! Keep you posted.

**Comment by 6pac** [comment]
Technically breaking the rules, but I think it will be fine in practice

**Comment by tatsujin1** [comment]
:)

**Pull request merged**
