### PR TITLE
fix: add grid object to all Formatter calls

### PR DESCRIPTION
**Pull request by ghiscoding**

### CODE REVIEW

**Comment by ghiscoding** [comment]
@6pac 
After doing these changes, my VSCode told me that the function `callFormatter()` is not used anywhere in the entire lib and is not a public function, see on this [line](https://github.com/6pac/SlickGrid/pull/558/files#diff-0218fbc2168a0b97bdcfa8d3eeba1ff37a8a9a09932779ddc250ef69c7b14d6eR3168).

Was that code something you added while working on the column auto-size of the width? 
Perhaps it's a function that is no longer necessary and should be removed? I don't see any references anywhere so...

**Comment by 6pac** [comment]
I have no idea where ```callFormatter``` comes from. It's not in any of my old repos, but I downloaded the current master back to Jun 2019 and it's still in there. I suspect someone added it at some point in a PR.   
Perhaps we should leave it for future investigation, it's not hurting anything. I don't object if you'd prefer to delete it, though.

**Comment by ghiscoding** [comment]
It actually comes from my commit 🤣 
It was copied over when I've starting merging the frozen feature from X-SlickGrid but there's few pieces that weren't used.
So I'm removing it since it was used in X-SlickGrid but not in our version, so it's safe to remove.

PR is ready

image

**Comment by ghiscoding** [comment]
@6pac 
I'm pretty much done with PRs for a while, would you mind doing another release with all PRs I've done recently.
Thanks Mate

**Pull request merged**
