### PR TITLE
fix(dataview): support ES6/ES2015 compilation

### PR DESCRIPTION
**Pull request by ghiscoding**
- in strict mode, we cannot set a function name dynamically but we can use `Object.defineProperty` with `writable` set to true to overcome this compilation issue.
- this should work with IE8 and up, I can only test with IE11 which I have installed

Reference from issue found in Angular-Slickgrid, [here](https://github.com/ghiscoding/angular-slickgrid-demos/pull/1) and [here](https://github.com/ghiscoding/Angular-Slickgrid/issues/266)

With this PR, it allows us to build and compile our project with ES6/ES2015

### CODE REVIEW

**Comment by 6pac** [comment]
Perfectly happy with the change, but there is a lot of whitespace noise in there.   
As I've said before, I don't have a problem with any particular whitespace/tabbing convention, but it's a lot of noise for the many people pulling to their customised repos, especially if they've formatted it all to *their* liking. Isn't there a way we can get Git to ignore whitespace changes when creating a diff/PR?

**Comment by ghiscoding** [comment]
That's the default of Visual Studio Code, if that's a problem I would have to delete the branch, disable VSCode auto-format on save and create a new branch

**Comment by 6pac** [comment]
I'm not really concerned about the whitespacing in your own code, I was just hoping there was a GIT setting to ignore whitespace when creating a diff for a PR. However, I had a look and it appears complicated.  
Out of interest, @ghiscoding, what process do you use to create a PR? Do you use the IDE-integrated tools in VS?  As for me, I've been using the Windows MinGW bash prompt for years - purely command line.

**Comment by ghiscoding** [comment]
is this what you're looking for to hide white space changes in a PR?

On the creation of a PR, I create a new branch in my editor, which is easy with VSCode, and then I push to the branch to your fork and from there I see a new orange alert telling that me that I can create a PR from this new branch and that is what I do and that's about it. Does that answer your question?

image

**Comment by 6pac** [comment]
definitely do this this evening, I just linted the codebase, finding a few quite serious issues and a lot of minor ones.  Have been a bit worried about the changes, so been testing rather extensively.

Chrome is so forgiving that it makes it easy to let code errors slide - I support a lot of agencies using IE exclusively, and it's always IE that is the canary in the coalmine, but that's on my own personal branch that is quite diverged from the main one now..

**Comment by 6pac** [comment]
No sorry, I probably overstated the problem, linting only found syntax errors and code smells. There were a couple of actual coding errors that would probably have thrown in IE, what's what I called 'serious'.  All other changes made after linting were only minor, like missing semicolons, vars with declarations in the wrong or multiple places, etc, but there were quite a few.  I didn't act on all the lint suggestions.

**Comment by 6pac** [comment]
Due to all the false positives, I don't really want to lint as part of the build process, but it's good to lint once a year, like a bit of a spring clean :-)

**Comment by 6pac** [comment]
Yes, the main folder, and plugins and controls subfolders. Would like to run it on the embedded scripts in the HTML files as well, but it wasn't easy to do that.

**Comment by ghiscoding** [comment]
@6pac 
I fixed the small merge conflict that happened after your last lint commit. Is there anything left for me to do on this PR? Let me know, thanks mate,

**Comment by 6pac** [comment]
I committed the contents of this PR separately, without the additional whitespace. Hope that works for you.

**Comment by ghiscoding** [comment]
ah ok I didn't notice that.. what worries me now is the new issue #424 that I just opened, the lint is causing multiple issues.

**Pull request closed without merging**
