### PR TITLE
chore: remove jQuery from all possible examples

### PR DESCRIPTION
**Pull request by ghiscoding**

### CODE REVIEW

**Comment by 6pac** [comment]
jeez, you are caning it (as we say in Australia)

**Comment by ghiscoding** [comment]
lol I do want to be done with this soon enough, summer is just about to start here 😉

**Comment by ghiscoding** [comment]
@6pac  BTW, I'm pretty much done at this point just some code cleanup and possibly look into troubleshooting 2 very old issues 
- selecting ForceFit Columns then unselecting it doesn't remove the feature
- the other one is the issue you've opened for frozen row top/bottom toggling

I'm not sure I can fix them or not, but I'll look into it. So I would say that after the coming weekend, I'll be ready for a beta release ;)

**Comment by 6pac** [comment]
I will try to have a look at the scrolling issue and the menu on the weekend, but I'm going camping for most of it so won't have a lot of time. It's winter here now but that just means 2C and night and 20C and sunny during the day rather than highs of 38C. Perfect camping weather!

Apologies I can't help more but very busy in the midst of a big project plus training up someone, and need occasional downtime to deal with it all.

**Pull request merged**
