### PR TITLE
New Feature - Row Detail panel

### LINKED ISSUE #128: rowdetails or nested grids
Hi team,
I need to Grid can show additional information below each grid row.
What can you advise? thank.

RowDetails.
rowdeteil
or Nested Grids
nested

like http://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/rowdetails.htm

### PR DESCRIPTION
**Pull request by ghiscoding**
Closes #128 for a Row Detail panel that can be toggled with a template that can be filled asynchronously

### CODE REVIEW

**Comment by ghiscoding** [comment]
@6pac, @SatanEnglish 
Here's our first version (or Beta) version of the Row Detail panel.

@6pac 
- You can have a quick look at it before merging. 
- These are all new files "plugin(js/css) + demo(html)"
- Nothing was touched on the core side. 
- **Final step** would be to link the Example16 in the Wiki demo page

Thanks to all who provided help and feedback. We now have another great feature to bring in more users for this awesome library called **SlickGrid**, used and love by many <3

**Comment by ghiscoding** [comment]
@6pac so we can actually do "Squash and Merge" with that green button in here. Have you used it before?

**Comment by ghiscoding** [comment]
@6pac,
I did the merge, please note that there was a small change to `slick.grid.js` as can be seen below

```diff
       addNewRowCssClass: "new-row",
       preserveCopiedSelectionOnPaste: false,
       showCellSelection: true,
-      viewportClass: null
+      viewportClass: null,
+	  minRowBuffer: 3
     };
 
     var columnDefaults = {
@@ -2045,7 +2046,7 @@ if (typeof Slick === "undefined") {
     function getRenderedRange(viewportTop, viewportLeft) {
       var range = getVisibleRange(viewportTop, viewportLeft);
       var buffer = Math.round(viewportH / options.rowHeight);
-      var minBuffer = 3;
+      var minBuffer = options.minRowBuffer;
 
       if (vScrollDir == -1) {
         range.top -= buffer;
```

**Comment by ghiscoding** [comment]
@6pac 
I updated the Wiki to include the Row Detail panel, the link is working. Also tested the `view source` link, it also work. All good :)

**Comment by 6pac** [comment]
Thanks. 2.3.13 now released.

I have manually created squash merges from the command line, but not used GitHub. 

I think they are a great idea though. I always thought [this](https://sandofsky.com/blog/git-workflow.html) was an excellent approach, but it's harder to enforce through an open source project without a lot of control-freakery

**Comment by ghiscoding** [comment]
Possibly another suggestions would be to use [Semantic Versioning](https://semver.org) (aka `semver`). I try to use in my own repos. Basically the concept is 
`x.y.z` where
- `x` defines a major (breaking changes)
- `y` defines a minor (new features)
- `z` defines patches (fixes only)
In your case, your version includes features but no breaking changes, if we follow `semver`, if would mean incrementing the second number, so `2.4.0`

By the way, very important (at least for me), I think you forgot to push `2.3.13` to NPM, which is the only way I get SlickGrid from ;)

Will read your article tomorrow, it's 1am here, time to sleep

**Comment by 6pac** [comment]
In theory we *are* using semver. The question always is, what comprises a 'feature'.
I usually restrict that to mean a pretty major thing (the last one was migration to this repo!).

But possibly we should update the minor ver more often.

Sorry about NPM, I updated the package.json but forgot to push it. Will do so now.

**Pull request merged**
